'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const test = require('node:test');
const { loadWithMockedElectron } = require('./helpers/mock-electron');

const assetChecker = require(path.join(__dirname, '..', 'plugins', 'asset-checker', 'index.js'));

function makeTmxWithTilesets(sources, layerXml = null) {
  const tilesetSources = Array.isArray(sources) ? sources : Array.from(arguments);
  const layers = layerXml || [
    ' <layer id="1" name="Ground" width="1" height="1">',
    '  <data encoding="csv">1</data>',
    ' </layer>',
  ].join('\n');
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<map version="1.10" orientation="orthogonal" width="1" height="1" tilewidth="8" tileheight="8" infinite="0">',
    ...tilesetSources.map((source, index) => ` <tileset firstgid="${index * 32 + 1}" source="${source}"/>`),
    layers,
    '</map>',
    '',
  ].join('\n');
}

function sampleAssets() {
  return [
    { type: 'IMAGE', name: 'img_title', sourcePath: 'gfx/title.png', resFile: 'resources.res' },
    { type: 'SPRITE', name: 'spr_hero', sourcePath: 'sprite/hero.png', width: '4', height: '4', resFile: 'resources.res' },
    { type: 'TILESET', name: 'tiles_stage', sourcePath: 'tiles/stage.png', resFile: 'hoge.res' },
    { type: 'PALETTE', name: 'tiles_stage_palette', sourcePath: 'tiles/stage.png', resFile: 'hoge.res' },
    { type: 'TILEMAP', name: 'map_stage', sourcePath: 'maps/stage.tmx', tileset: 'tiles_stage', resFile: 'hoge.res' },
    { type: 'MAP', name: 'scroll_stage', sourcePath: 'maps/scroll.tmx', tileset: 'Ground', resFile: 'hoge.res' },
    { type: 'XGM2', name: 'bgm_stage', sourcePath: 'music/stage.vgm' },
    { type: 'XGM', name: 'bgm_legacy', sourcePath: 'music/legacy.xgm' },
    { type: 'WAV', name: 'bgm_pcm', sourcePath: 'bgm/pcm.wav', outRate: '6650' },
    { type: 'WAV', name: 'se_hit', sourcePath: 'sfx/hit.wav' },
  ];
}

test('asset-checker declares a builder role', () => {
  const userData = fs.mkdtempSync(path.join(os.tmpdir(), 'md-editor-asset-checker-plugin-test-'));
  const pluginManager = loadWithMockedElectron(path.join(__dirname, '..', 'plugin-manager.js'), { userData });
  const plugin = pluginManager.listPlugins().find((item) => item.id === 'asset-checker');

  assert.ok(plugin);
  assert.equal(plugin.name, 'アセットチェッカー');
  assert.equal(plugin.roles.length, 1);
  assert.equal(plugin.roles[0].id, 'builder');
  assert.deepEqual(plugin.pluginTypes, ['build']);
});

test('asset-checker groups supported assets and filters non-BGM wav files', () => {
  const grouped = assetChecker.collectAssets(sampleAssets());

  assert.deepEqual(grouped.images.map((entry) => entry.name), ['img_title']);
  assert.deepEqual(grouped.sprites.map((entry) => entry.name), ['spr_hero']);
  assert.deepEqual(grouped.tilemaps.map((entry) => entry.name), ['map_stage', 'scroll_stage']);
  assert.deepEqual(grouped.bgms.map((entry) => entry.name), ['bgm_legacy', 'bgm_pcm', 'bgm_stage']);
  assert.equal(grouped.bgms.some((entry) => entry.name === 'se_hit'), false);
});

test('asset-checker generator renders a SGDK 2.11 single-file checker', () => {
  const result = assetChecker.generateSource(sampleAssets());

  assert.equal(result.ok, true);
  assert.match(result.sourceCode, /Generated by asset-checker v0\.1\.0/);
  assert.match(result.sourceCode, /#include "resources\.h"\n#include "hoge\.h"/);
  assert.match(result.sourceCode, /#define IMAGE_COUNT 1/);
  assert.match(result.sourceCode, /#define SPRITE_COUNT 1/);
  assert.match(result.sourceCode, /#define TILEMAP_COUNT 2/);
  assert.match(result.sourceCode, /#define BGM_COUNT 3/);
  assert.match(result.sourceCode, /int main\(bool hardReset\)/);
  assert.match(result.sourceCode, /static u16 tile_scroll_speed = 1;/);
  assert.match(result.sourceCode, /static s32 tile_scroll_x = 0;/);
  assert.doesNotMatch(result.sourceCode, /wrap_add\(u32 value, s16 delta, u32 limit\)/);
  assert.doesNotMatch(result.sourceCode, /tilemap_scroll_limit_x\(const TilemapEntry\* entry\)/);
  assert.match(result.sourceCode, /static bool sprite_playing = TRUE;/);
  assert.match(result.sourceCode, /static bool bgm_playing = TRUE;/);
  assert.match(result.sourceCode, /sprite_animation_count\(void\)/);
  assert.match(result.sourceCode, /definition->numAnimation/);
  assert.match(result.sourceCode, /clamp_sprite_animation\(\);/);
  assert.match(result.sourceCode, /sprite_anim = \(u16\)\(\(sprite_anim \+ 1\) % sprite_animation_count\(\)\)/);
  assert.match(result.sourceCode, /VDP_drawImageEx\(/);
  assert.match(result.sourceCode, /PAL_setPalette\(PAL0, palette_grey, CPU\)/);
  assert.match(result.sourceCode, /VDP_setTextPalette\(PAL0\)/);
  assert.match(result.sourceCode, /PAL_setPalette\(PAL1, image_entries\[image_index\]\.image->palette->data, CPU\)/);
  assert.match(result.sourceCode, /TILE_ATTR_FULL\(PAL1, FALSE, FALSE, FALSE, TILE_BASE_INDEX\)/);
  assert.match(result.sourceCode, /,\s*0,\s*0,\s*FALSE,\s*DMA\s*\)/);
  assert.match(result.sourceCode, /SPR_addSprite/);
  assert.match(result.sourceCode, /add_tilemap_overlay_sprite\(const TilemapEntry\* entry\)/);
  assert.match(result.sourceCode, /SPR_addSprite\(sprite_entries\[sprite_index\]\.sprite, 144, 104, TILE_ATTR\(PAL3, FALSE, FALSE, FALSE\)\)/);
  assert.match(result.sourceCode, /add_tilemap_overlay_sprite\(entry\);/);
  assert.match(result.sourceCode, /category == CATEGORY_TILEMAP && current_sprite/);
  assert.match(result.sourceCode, /PAL_setPalette\(PAL2, sprite_entries\[sprite_index\]\.sprite->palette->data, CPU\)/);
  assert.match(result.sourceCode, /PAL_setPalette\(PAL3, sprite_entries\[sprite_index\]\.sprite->palette->data, CPU\)/);
  assert.match(result.sourceCode, /TILE_ATTR\(PAL3, FALSE, FALSE, FALSE\)/);
  assert.match(result.sourceCode, /SPR_setAnim/);
  assert.match(result.sourceCode, /VDP_setTileMapEx/);
  assert.match(result.sourceCode, /draw_repeated_tilemap\(entry\)/);
  assert.match(result.sourceCode, /#define TILEMAP_MAX_TILESETS 8/);
  assert.match(result.sourceCode, /#define TILEMAP_MAX_PALETTES 3/);
  assert.match(result.sourceCode, /const TileSet\* tilesets\[TILEMAP_MAX_TILESETS\]/);
  assert.match(result.sourceCode, /u16 tileOffsets\[TILEMAP_MAX_TILESETS\]/);
  assert.match(result.sourceCode, /u16 paletteSlots\[TILEMAP_MAX_TILESETS\]/);
  assert.match(result.sourceCode, /const Palette\* palettes\[TILEMAP_MAX_PALETTES\]/);
  assert.doesNotMatch(result.sourceCode, /collisionData/);
  assert.doesNotMatch(result.sourceCode, /show_collision/);
  assert.doesNotMatch(result.sourceCode, /draw_collision_overlay/);
  assert.match(result.sourceCode, /for \(u16 i = 0; \(i < entry->tilesetCount\) && \(i < TILEMAP_MAX_TILESETS\); i\+\+\)/);
  assert.match(result.sourceCode, /MAP_create/);
  assert.match(result.sourceCode, /static u16 tilemap_preview_buffer\[TILEMAP_VIEW_META_W \* TILEMAP_VIEW_META_H \* 4\]/);
  assert.match(result.sourceCode, /redraw_map_preview\(entry, FALSE\)/);
  assert.match(result.sourceCode, /MAP_getTilemapRect\(current_map/);
  assert.match(result.sourceCode, /tilemap_palette_for_tile_index\(const TilemapEntry\* entry, u16 rawIndex, u16 encodedPalette\)/);
  assert.match(result.sourceCode, /entry->paletteSlots\[i\]/);
  assert.match(result.sourceCode, /VDP_setTileMapDataColumnFast\(BG_B/);
  assert.match(result.sourceCode, /VDP_setTileMapDataRow\(BG_B/);
  assert.match(result.sourceCode, /VDP_setHorizontalScrollVSync\(BG_B/);
  assert.doesNotMatch(result.sourceCode, /MAP_scrollTo/);
  assert.match(result.sourceCode, /MAP_release/);
  assert.match(result.sourceCode, /PAL_setPalette\(\(u16\)\(PAL1 \+ i\), entry->palettes\[i\]->data, CPU\)/);
  assert.match(result.sourceCode, /TILE_ATTR_FULL\(PAL1, FALSE, FALSE, FALSE, TILE_BASE_INDEX\)/);
  assert.match(result.sourceCode, /\{ "map_stage \(TILEMAP\)", TILEMAP_KIND_TILEMAP, &map_stage, NULL, \{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL \}, \{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL \}, 0, NULL, \{ &tiles_stage, NULL, NULL, NULL, NULL, NULL, NULL, NULL \}, \{ 0, 0, 0, 0, 0, 0, 0, 0 \}, \{ 0, 0, 0, 0, 0, 0, 0, 0 \}, 1, \{ &tiles_stage_palette, NULL, NULL \}, 1, 0, 0 \}/);
  assert.match(result.sourceCode, /\{ "scroll_stage \(MAP\)", TILEMAP_KIND_MAP, NULL, &scroll_stage, \{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL \}, \{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL \}, 0, NULL, \{ &tiles_stage, NULL, NULL, NULL, NULL, NULL, NULL, NULL \}, \{ 0, 0, 0, 0, 0, 0, 0, 0 \}, \{ 0, 0, 0, 0, 0, 0, 0, 0 \}, 1, \{ &tiles_stage_palette, NULL, NULL \}, 1, 0, 0 \}/);
  assert.match(result.sourceCode, /XGM2_play\(entry->data\)/);
  assert.doesNotMatch(result.sourceCode, /XGM2_loadDriver\(TRUE\)/);
  assert.match(result.sourceCode, /Z80_loadDriver\(Z80_DRIVER_XGM2, TRUE\)/);
  assert.match(result.sourceCode, /XGM2_playPCMEx\(entry->data, entry->size, SOUND_PCM_CH1, 15, entry->halfRate, bgm_loop\)/);
  assert.match(result.sourceCode, /active_bgm_kind = entry->kind/);
  assert.match(result.sourceCode, /load_bgm_status[\s\S]*if \(bgm_playing && BGM_COUNT > 0\) play_bgm\(\);/);
  assert.doesNotMatch(result.sourceCode, /se_hit/);
});

test('asset-checker accepts empty categories but rejects empty projects', () => {
  const imageOnly = assetChecker.generateSource([
    { type: 'IMAGE', name: 'img_only', sourcePath: 'gfx/only.png' },
  ]);
  const empty = assetChecker.generateSource([]);

  assert.equal(imageOnly.ok, true);
  assert.match(imageOnly.sourceCode, /#define SPRITE_COUNT 0/);
  assert.match(imageOnly.sourceCode, /\{ "none", NULL \}/);
  const mapOnly = assetChecker.generateSource([
    { type: 'MAP', name: 'map_only', sourcePath: 'maps/only.tmx' },
    { type: 'TILESET', name: 'tiles_only', sourcePath: 'tilesets/only.tsx' },
  ]);
  assert.equal(mapOnly.ok, true);
  assert.match(mapOnly.sourceCode, /#define TILEMAP_COUNT 1/);
  assert.match(mapOnly.sourceCode, /TILEMAP_KIND_MAP, NULL, &map_only/);
  assert.match(mapOnly.sourceCode, /&map_only, \{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL \}, \{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL \}, 0, NULL, \{ &tiles_only, NULL, NULL, NULL, NULL, NULL, NULL, NULL \}, \{ 0, 0, 0, 0, 0, 0, 0, 0 \}, \{ 0, 0, 0, 0, 0, 0, 0, 0 \}, 1, \{ NULL, NULL, NULL \}, 0, 0, 0/);
  assert.equal(empty.ok, false);
  assert.match(empty.error, /アセットが見つかりません/);
});

test('asset-checker resolves MAP tilesets from TMX source instead of layer_id', () => {
  const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), 'md-editor-asset-checker-tmx-test-'));
  fs.mkdirSync(path.join(projectDir, 'res', 'maps'), { recursive: true });
  fs.writeFileSync(
    path.join(projectDir, 'res', 'maps', 'map001.tmx'),
    makeTmxWithTilesets(['../tilesets/enemy01.tsx', '../tilesets/enemy02.tsx']),
    'utf-8',
  );
  const assets = [
    { type: 'MAP', name: 'map001', sourcePath: 'maps/map001.tmx', tileset: 'Ground', resFile: 'resources.res' },
    { type: 'PALETTE', name: 'enemy01_palette', sourcePath: 'tilesets/enemy01.png', resFile: 'resources.res' },
    { type: 'TILESET', name: 'enemy02', sourcePath: 'tilesets/enemy02.tsx', resFile: 'resources.res' },
    { type: 'PALETTE', name: 'enemy02_palette', sourcePath: 'tilesets/enemy02.png', resFile: 'resources.res' },
  ];

  const resolved = assetChecker.findTilesetsForTilemap(assets[0], assets.filter((asset) => asset.type === 'TILESET'), { projectDir });
  const result = assetChecker.generateSource(assets, { projectDir });

  assert.deepEqual(resolved.map((asset) => asset.name), ['map001_tileset0']);
  assert.equal(result.ok, true);
  assert.doesNotMatch(result.sourceCode, /static const u16 map001_checker_layer/);
  assert.match(result.sourceCode, /\{ "map001 \(MAP\)", TILEMAP_KIND_MAP, NULL, &map001, \{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL \}, \{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL \}, 0, NULL, \{ &map001_tileset0, NULL, NULL, NULL, NULL, NULL, NULL, NULL \}, \{ 0, 0, 0, 0, 0, 0, 0, 0 \}, \{ 0, 0, 0, 0, 0, 0, 0, 0 \}, 1, \{ &enemy01_palette, NULL, NULL \}, 1, 1, 1 \}/);
  assert.doesNotMatch(result.sourceCode, /map001 \(MAP no tileset\)/);
});

test('asset-checker keeps MAP layer selection delegated to ResComp layer_id', () => {
  const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), 'md-editor-asset-checker-composite-test-'));
  fs.mkdirSync(path.join(projectDir, 'res', 'maps'), { recursive: true });
  fs.writeFileSync(
    path.join(projectDir, 'res', 'maps', 'map001.tmx'),
    [
      '<?xml version="1.0" encoding="UTF-8"?>',
      '<map version="1.10" orientation="orthogonal" width="2" height="1" tilewidth="8" tileheight="8" infinite="0">',
      ' <tileset firstgid="1" source="../tilesets/enemy01.tsx"/>',
      ' <layer id="1" name="Ground" width="2" height="1"><data encoding="csv">1,2</data></layer>',
      ' <layer id="2" name="Overlay" width="2" height="1"><data encoding="csv">0,3</data></layer>',
      ' <layer id="3" name="Overlay priority" width="2" height="1"><data encoding="csv">4,0</data></layer>',
      ' <layer id="4" name="Collision" width="2" height="1"><data encoding="csv">1,1</data></layer>',
      '</map>',
      '',
    ].join('\n'),
    'utf-8',
  );

  const result = assetChecker.generateSource([
    { type: 'MAP', name: 'map001', sourcePath: 'maps/map001.tmx', tileset: 'Ground', resFile: 'resources.res' },
    { type: 'TILESET', name: 'enemy01', sourcePath: 'tilesets/enemy01.tsx', resFile: 'resources.res' },
  ], { projectDir });

  assert.equal(result.ok, true);
  assert.doesNotMatch(result.sourceCode, /static const u16 map001_checker_layer/);
  assert.match(result.sourceCode, /\{ "map001 \(MAP\)", TILEMAP_KIND_MAP, NULL, &map001, \{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL \}, \{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL \}, 0, NULL, \{/);
});

test('asset-checker previews sibling MAP layer_id entries individually', () => {
  const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), 'md-editor-asset-checker-layer-tilesets-test-'));
  fs.mkdirSync(path.join(projectDir, 'res', 'maps'), { recursive: true });
  fs.mkdirSync(path.join(projectDir, 'res', 'tilesets'), { recursive: true });
  fs.writeFileSync(
    path.join(projectDir, 'res', 'maps', 'map001.tmx'),
    [
      '<?xml version="1.0" encoding="UTF-8"?>',
      '<map version="1.10" orientation="orthogonal" width="2" height="1" tilewidth="8" tileheight="8" infinite="0">',
      ' <tileset firstgid="1" source="../tilesets/bga.tsx"/>',
      ' <tileset firstgid="897" source="../tilesets/enemies.tsx"/>',
      ' <layer id="1" name="Ground" width="2" height="1"><data encoding="csv">1,2</data></layer>',
      ' <layer id="2" name="Layer 2" width="2" height="1"><data encoding="csv">897,0</data></layer>',
      ' <layer id="3" name="Layer 2 priority" width="2" height="1"><data encoding="csv">1,1</data></layer>',
      ' <layer id="4" name="Collision" width="2" height="1"><data encoding="csv">1,1</data></layer>',
      '</map>',
      '',
    ].join('\n'),
    'utf-8',
  );
  fs.writeFileSync(path.join(projectDir, 'res', 'tilesets', 'bga.tsx'), '<tileset tilecount="896"></tileset>', 'utf-8');
  fs.writeFileSync(path.join(projectDir, 'res', 'tilesets', 'enemies.tsx'), '<tileset tilecount="24"></tileset>', 'utf-8');
  const assets = [
    { type: 'MAP', name: 'map001', sourcePath: 'maps/map001.tmx', tileset: 'Ground', resFile: 'maps.res' },
    { type: 'MAP', name: 'map001_layer_2', sourcePath: 'maps/map001.tmx', tileset: 'Layer 2', resFile: 'maps.res' },
    { type: 'MAP', name: 'map001_layer_2_priority', sourcePath: 'maps/map001.tmx', tileset: 'Layer 2 priority', resFile: 'maps.res' },
    { type: 'MAP', name: 'map001_collision', sourcePath: 'maps/map001.tmx', tileset: 'Collision', resFile: 'maps.res' },
    { type: 'TILESET', name: 'bga', sourcePath: 'tilesets/bga.tsx', resFile: 'resources.res' },
    { type: 'PALETTE', name: 'bga_palette', sourcePath: 'tilesets/bga.png', resFile: 'resources.res' },
    { type: 'TILESET', name: 'enemies', sourcePath: 'tilesets/enemies.tsx', resFile: 'resources.res' },
    { type: 'PALETTE', name: 'enemies_palette', sourcePath: 'tilesets/enemies.png', resFile: 'resources.res' },
  ];

  const result = assetChecker.generateSource(assets, { projectDir });

  assert.equal(result.ok, true);
  assert.match(result.sourceCode, /#define TILEMAP_COUNT 4/);
  assert.doesNotMatch(result.sourceCode, /static const u16 map001_checker_layer/);
  assert.match(result.sourceCode, /\{ "map001 \(MAP\)", TILEMAP_KIND_MAP, NULL, &map001, \{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL \}, \{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL \}, 0, NULL, \{ &bga, NULL, NULL, NULL, NULL, NULL, NULL, NULL \}/);
  assert.match(result.sourceCode, /\{ "map001_layer_2 \(MAP\)", TILEMAP_KIND_MAP, NULL, NULL, \{ &map001_layer_2, NULL, NULL, NULL, NULL, NULL, NULL, NULL \}, \{ &map001_layer_2_priority, NULL, NULL, NULL, NULL, NULL, NULL, NULL \}, 1, NULL, \{ &enemies, NULL, NULL, NULL, NULL, NULL, NULL, NULL \}/);
  assert.match(result.sourceCode, /\{ "map001_layer_2_priority \(MAP\)", TILEMAP_KIND_MAP, NULL, NULL, \{ &map001_layer_2, NULL, NULL, NULL, NULL, NULL, NULL, NULL \}, \{ &map001_layer_2_priority, NULL, NULL, NULL, NULL, NULL, NULL, NULL \}, 1, NULL, \{ &enemies, NULL, NULL, NULL, NULL, NULL, NULL, NULL \}/);
});

test('asset-checker build hook limits SGDK source scan to generated main.c', () => {
  const messages = [];
  const result = assetChecker.onBuildStart(
    { projectDir: 'project' },
    { logger: { info: (message) => messages.push(message) } },
  );

  assert.equal(result.ok, true);
  assert.deepEqual(result.makeVariables, { SRC_C: 'src/main.c' });
  assert.match(messages[0], /asset-checker build start/);
});
