'use strict';

const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const test = require('node:test');
const { encodeRgbaPng, quantizeDmg, quantizeGbc } = require('../pce-vn-gb-studio-image');
const { packAtomicUnits, parseBdf } = require('../pce-vn-gb-studio-font');
const { convertPsgToMod } = require('../pce-vn-gb-studio-music');
const { modeSceneId, speakerToneFrequency } = require('../pce-vn-gb-studio-project');
const { EXPORTER_FORMAT, MANIFEST_FILE, SUPPORTED_GB_STUDIO_VERSIONS, generateGbStudioProject, inspectGbStudioExport, inspectGbStudioInstallation, isSupportedGbStudioInstallation, normalizeGbStudioExecutablePath, readAsarEntry, validateGbStudioProject } = require('../pce-vn-gb-studio-exporter');
const cli = require('../tools/dev/pce-vn-gb-studio-export');

const GB_STUDIO = { version: '4.3.1', engineVersion: '4.3.0-e1', executablePath: 'fixture-gb-studio.exe', verified: true };
const GB_STUDIO_432 = { ...GB_STUDIO, version: '4.3.2' };
function digest(file) { return crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'); }

function fixturePng() {
  const width = 32; const height = 32; const rgba = new Uint8Array(width * height * 4);
  for (let y = 0; y < height; y += 1) for (let x = 0; x < width; x += 1) { const at = (y * width + x) * 4; const shade = (Math.floor(x / 8) + Math.floor(y / 8)) % 4; const colors = [[240, 230, 180], [180, 180, 100], [80, 110, 90], [10, 25, 30]]; rgba.set([...colors[shade], 255], at); }
  return encodeRgbaPng({ width, height, rgba });
}

function makeFixture(overrides = {}) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'pce-vn-gb-export-')); fs.mkdirSync(path.join(root, 'assets', 'images'), { recursive: true });
  const project = { coreId: 'pc-engine', title: '変換テスト', romName: 'gbvn_test', author: 'Codex' }; fs.writeFileSync(path.join(root, 'project.json'), JSON.stringify(project)); fs.writeFileSync(path.join(root, 'assets', 'images', 'bg.png'), fixturePng());
  const assets = { version: 2, assets: [{ id: 'bg', type: 'image', name: 'BG', source: 'assets/images/bg.png', options: { kind: 'background', width: 32, height: 32 } }, { id: 'song', type: 'psg-song', name: 'Song', source: '', options: { kind: 'song', bpm: 120, speed: 6, steps: 65, loop: true, loopPoint: 17, pattern: [{ step: 0, channel: 0, note: 'C4', volume: 20 }, { step: 17, channel: 2, note: 'E4', volume: 12 }] } }, ...(overrides.assets || [])] };
  const scenes = overrides.scenes || { version: 2, settings: {}, startScene: 'opening', scenes: [{ id: 'opening', name: 'Opening', commands: [{ type: 'background', assetId: 'bg', transition: 'fade', fadeInFrames: 30, fadeOutFrames: 30 }, { type: 'audio', kind: 'psg', action: 'play', assetId: 'song' }, { type: 'message', speaker: 'チカ', text: 'こんにちは。変換テストです。' }, { type: 'choice', variableName: 'route', choices: [{ label: '右へ行く', value: 7, targetSceneId: 'right' }, { label: '左へ行く', value: 9, targetSceneId: 'left' }] }] }, { id: 'right', name: 'Right', commands: [{ type: 'background', assetId: 'bg' }, { type: 'message', speaker: '', text: '右を選びました。' }, { type: 'jump', sceneId: 'opening' }] }, { id: 'left', name: 'Left', commands: [{ type: 'background', assetId: 'bg' }, { type: 'message', speaker: '', text: '左を選びました。' }, { type: 'wait', frames: 30 }, { type: 'jump', sceneId: 'opening' }] }] };
  fs.writeFileSync(path.join(root, 'assets', 'pce-assets.json'), JSON.stringify(assets)); fs.writeFileSync(path.join(root, 'assets', 'pce-vn-scenes.json'), JSON.stringify(scenes)); return { root, project, assets, scenes };
}

test('GB Studio installation metadata accepts 4.3.1/4.3.2 with engine 4.3.0-e1 and unquotes executable paths', () => {
  assert.deepEqual(SUPPORTED_GB_STUDIO_VERSIONS, ['4.3.1', '4.3.2']); assert.deepEqual(inspectGbStudioInstallation(GB_STUDIO), GB_STUDIO); assert.equal(isSupportedGbStudioInstallation(GB_STUDIO), true); assert.equal(isSupportedGbStudioInstallation(GB_STUDIO_432), true); assert.equal(isSupportedGbStudioInstallation({ ...GB_STUDIO_432, engineVersion: 'wrong' }), false); const executable = path.resolve('fixture-gb-studio.exe'); assert.equal(normalizeGbStudioExecutablePath(`"${executable}"`), executable);
});

test('Electron preflight reads GB Studio metadata without patched-fs ENOENT', async () => {
  const asar = require('@electron/asar'); const installRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'pce-vn-gb-electron-asar-')); const source = path.join(installRoot, 'source'); const resources = path.join(installRoot, 'resources'); const executable = path.join(installRoot, 'gb-studio.exe'); fs.mkdirSync(path.join(source, 'appData', 'engine'), { recursive: true }); fs.mkdirSync(resources); fs.writeFileSync(executable, 'fixture'); fs.writeFileSync(path.join(source, 'package.json'), JSON.stringify({ version: '4.3.2' })); fs.writeFileSync(path.join(source, 'appData', 'engine', 'engine.json'), JSON.stringify({ version: '4.3.0-e1' })); await asar.createPackage(source, path.join(resources, 'app.asar'));
  const exporterPath = path.join(__dirname, '..', 'pce-vn-gb-studio-exporter.js'); const script = 'const result=require(' + JSON.stringify(exporterPath) + ').inspectGbStudioInstallation(' + JSON.stringify(executable) + ');process.stdout.write(JSON.stringify(result));';
  const child = require('node:child_process').spawnSync(require('electron'), ['-e', script], { encoding: 'utf-8', env: { ...process.env, ELECTRON_RUN_AS_NODE: '1' } });
  assert.equal(child.status, 0, child.stderr); const result = JSON.parse(child.stdout); assert.equal(result.verified, true, JSON.stringify(result)); assert.equal(result.version, '4.3.2'); assert.equal(result.engineVersion, '4.3.0-e1');
});

test('image quantizers enforce GBC 7x4 colors and DMG 4 shades/192 tiles', () => {
  const image = require('../pce-vn-gb-studio-image').readRgbaPng(fixturePng()); const gbc = quantizeGbc(image); const dmg = quantizeDmg(image, { fullScreen: true });
  assert.ok(gbc.audit.palettes <= 7); assert.ok(gbc.audit.maxColorsPerTile <= 4); assert.equal(dmg.audit.meaningfulShades, 4); assert.ok(dmg.audit.uniqueTiles <= 192);
});

test('BDF parser and atomic font page limit are deterministic', () => {
  const glyphs = parseBdf('STARTFONT 2.1\nSTARTCHAR A\nENCODING 65\nBBX 8 8 0 0\nBITMAP\n18\n24\n42\n7E\n42\n42\n42\n00\nENDCHAR\nENDFONT\n'); assert.equal(glyphs.get('A').length, 64); assert.equal(packAtomicUnits([{ id: 'a', text: 'abc' }, { id: 'b', text: 'bcd' }]).pages.length, 1); assert.throws(() => packAtomicUnits([{ id: 'overflow', text: Array.from({ length: 223 }, (_, index) => String.fromCodePoint(0x400 + index)).join('') }]), (error) => error.code === 'GBVN_FONT_ATOMIC_UNIT_OVERFLOW');
});

test('PSG MOD preserves a non-zero loop boundary and audits channel conflicts', () => {
  const result = convertPsgToMod({ id: 'music', options: { steps: 65, loop: true, loopPoint: 17, bpm: 120, speed: 6, pattern: [{ step: 0, channel: 1, note: 'C4', volume: 4 }, { step: 0, channel: 3, note: 'E4', volume: 12 }, { step: 17, channel: 0, note: 'G4', volume: 16 }] } }); assert.equal(result.buffer.subarray(1080, 1084).toString('ascii'), 'M.K.'); assert.equal(result.audit.loop.sourceStep, 17); assert.equal(result.audit.loop.targetOrder, 1); assert.equal(result.audit.droppedEvents.length, 1);
});

test('preflight and generation emit one mixed ROM project with dual graphs and audits', () => {
  const fixture = makeFixture(); const sourceFiles = ['project.json', 'assets/pce-assets.json', 'assets/pce-vn-scenes.json', 'assets/images/bg.png'].map((relative) => [relative, digest(path.join(fixture.root, relative))]); const inspection = inspectGbStudioExport({ projectDir: fixture.root, settings: { warningsAcknowledged: true }, gbStudio: GB_STUDIO }); assert.equal(inspection.ok, true, JSON.stringify(inspection.errors)); assert.equal(inspection.summary.outputScenes, 7); assert.equal(inspection.summary.musicTracks, 1);
  const outputDir = path.join(fixture.root, 'gb-output'); const result = generateGbStudioProject({ inspection, outputDir }); assert.equal(result.ok, true, JSON.stringify(result.validation.errors)); assert.ok(fs.existsSync(result.descriptorPath)); assert.ok(fs.existsSync(path.join(outputDir, MANIFEST_FILE))); assert.ok(fs.existsSync(path.join(outputDir, 'plugins', 'pce-vn-dialogue-prepare', 'engine', 'engine.json'))); assert.ok(fs.existsSync(path.join(outputDir, 'build', 'qa', 'backgrounds-gbc.png'))); assert.ok(fs.existsSync(path.join(outputDir, 'build', 'qa', 'music-audit.json')));
  assert.ok(fs.existsSync(path.join(outputDir, 'build', 'qa', 'conversion-audit.json')));
  const settings = JSON.parse(fs.readFileSync(path.join(outputDir, 'project', 'settings.gbsres'))); assert.equal(settings.colorMode, 'mixed'); assert.equal(settings.defaultBackgroundPaletteIds[7], 'default-ui'); const validation = validateGbStudioProject({ outputDir }); assert.equal(validation.ok, true, JSON.stringify(validation.errors)); sourceFiles.forEach(([relative, hash]) => assert.equal(digest(path.join(fixture.root, relative)), hash));
  const manifest = JSON.parse(fs.readFileSync(path.join(outputDir, MANIFEST_FILE))); assert.equal(manifest.format, EXPORTER_FORMAT); assert.equal(manifest.conversion.font.id, 'builtin:misaki-gothic-8x8'); assert.ok(manifest.ownedPaths.length > 20);
});

test('message voice is automatically replaced by a stable speaker text tone', () => {
  const fixture = makeFixture({ assets: [{ id: 'voice-line', type: 'adpcm', name: 'Voice', source: '', options: {} }], scenes: { version: 2, startScene: 'opening', scenes: [{ id: 'opening', commands: [{ type: 'background', assetId: 'bg' }, { type: 'message', speaker: 'チカ', text: '音声つきです。', voiceAssetId: 'voice-line' }] }] } });
  const inspection = inspectGbStudioExport({ projectDir: fixture.root, settings: { warningsAcknowledged: true }, gbStudio: GB_STUDIO }); assert.equal(inspection.ok, true, JSON.stringify(inspection.errors)); assert.equal(inspection.requirements.audioSubstitutions.length, 0); assert.equal(inspection.requirements.automaticVoiceSubstitutions.length, 1); assert.equal(inspection.requirements.automaticVoiceSubstitutions[0].frequency, speakerToneFrequency('チカ'));
  const outputDir = path.join(fixture.root, 'gb-output'); generateGbStudioProject({ inspection, outputDir }); const audit = JSON.parse(fs.readFileSync(path.join(outputDir, 'build', 'qa', 'conversion-audit.json'))); assert.deepEqual(audit.automaticVoiceSubstitutions, inspection.requirements.automaticVoiceSubstitutions);
});

test('state, labels, branches, input modes, SpriteText, and shake are emitted without omission', () => {
  const fixture = makeFixture({ scenes: { version: 2, startScene: 'opening', scenes: [{ id: 'opening', commands: [{ type: 'background', assetId: 'bg' }, { type: 'variable', variableName: 'score', operation: 'define', value: 2 }, { type: 'variable', variableName: 'score', operation: 'add', value: 3 }, { type: 'variable', variableName: 'roll', operation: 'random', min: 1, max: 6 }, { type: 'if', variableName: 'score', operator: 'gte', value: 2, targetLabel: 'has_score', elseLabel: 'no_score' }, { type: 'label', name: 'has_score' }, { type: 'switch', variableName: 'score', cases: [{ value: 5, targetLabel: 'route_a' }], defaultLabel: 'no_score' }, { type: 'label', name: 'route_a' }, { type: 'inputcheck', mode: 'async', buttons: ['run'], targetLabel: 'end' }, { type: 'inputcheck', mode: 'cancel' }, { type: 'inputcheck', mode: 'sync', buttons: ['i', 'right'], targetLabel: 'end' }, { type: 'label', name: 'no_score' }, { type: 'goto', targetLabel: 'end' }, { type: 'label', name: 'end' }, { type: 'spritetext', text: '状態OK', x: 8, y: 8 }, { type: 'effect', effect: 'shake', frames: 10, intensity: 2 }, { type: 'message', text: '制御フロー完了。' }] }] } }); const inspection = inspectGbStudioExport({ projectDir: fixture.root, settings: { warningsAcknowledged: true }, gbStudio: GB_STUDIO }); assert.equal(inspection.ok, true, JSON.stringify(inspection.errors)); assert.equal(inspection.omissions.length, 0); const outputDir = path.join(fixture.root, 'gb-output-control'); generateGbStudioProject({ inspection, outputDir }); const scripts = fs.readdirSync(path.join(outputDir, 'project', 'scenes'), { recursive: true }).filter((name) => String(name).endsWith('.gbsres')).map((name) => fs.readFileSync(path.join(outputDir, 'project', 'scenes', name), 'utf-8')).join('\n'); ['EVENT_SET_VALUE', 'EVENT_VARIABLE_MATH', 'EVENT_IF', 'EVENT_SET_INPUT_SCRIPT', 'EVENT_REMOVE_INPUT_SCRIPT', 'EVENT_AWAIT_INPUT', 'EVENT_TEXT_DRAW', 'EVENT_CAMERA_SHAKE'].forEach((command) => assert.match(scripts, new RegExp(command))); assert.match(scripts, /"other": "rnd"/);
});

test('targetless async input resumes after the following sync gate and clears all input callbacks', () => {
  const fixture = makeFixture({ scenes: { version: 2, startScene: 'entry', scenes: [{ id: 'entry', name: 'Entry', commands: [{ type: 'background', assetId: 'bg' }, { type: 'inputcheck', mode: 'async', buttons: ['run', 'i'], targetLabel: '' }, { type: 'inputcheck', mode: 'async', buttons: ['right'], targetLabel: 'next' }, { type: 'inputcheck', mode: 'sync', buttons: ['left'], targetLabel: 'previous' }, { type: 'jump', sceneId: 'arrival' }, { type: 'label', name: 'next' }, { type: 'jump', sceneId: 'next_scene' }, { type: 'label', name: 'previous' }, { type: 'jump', sceneId: 'previous_scene' }] }, { id: 'arrival', commands: [{ type: 'background', assetId: 'bg' }, { type: 'message', text: '開始' }] }, { id: 'next_scene', commands: [{ type: 'background', assetId: 'bg' }, { type: 'message', text: '次' }] }, { id: 'previous_scene', commands: [{ type: 'background', assetId: 'bg' }, { type: 'message', text: '前' }] }] } });
  const inspection = inspectGbStudioExport({ projectDir: fixture.root, settings: { warningsAcknowledged: true }, gbStudio: GB_STUDIO_432 }); assert.equal(inspection.ok, true, JSON.stringify(inspection.errors)); const outputDir = path.join(fixture.root, 'gb-output-input-resume'); generateGbStudioProject({ inspection, outputDir }); const resources = fs.readdirSync(path.join(outputDir, 'project', 'scenes'), { recursive: true }).filter((name) => String(name).endsWith('.gbsres')).map((name) => JSON.parse(fs.readFileSync(path.join(outputDir, 'project', 'scenes', name), 'utf-8'))); const entry = resources.find((resource) => resource.name === 'Entry [GBC]'); assert.ok(entry); const startInput = entry.script.find((item) => item.command === 'EVENT_SET_INPUT_SCRIPT' && item.args.input.includes('a') && item.args.input.includes('start')); assert.ok(startInput); const startChildren = startInput.children.true; const cleanup = startChildren.find((item) => item.command === 'EVENT_REMOVE_INPUT_SCRIPT'); assert.deepEqual(cleanup.args.input, ['a', 'b', 'start', 'select', 'up', 'down', 'left', 'right']); const startSwitch = startChildren.find((item) => item.command === 'EVENT_SWITCH_SCENE'); assert.equal(startSwitch.args.sceneId, modeSceneId(inspection._model.graph.firstTargets.arrival, 'gbc')); const awaitIndex = entry.script.findIndex((item) => item.command === 'EVENT_AWAIT_INPUT' && item.args.input.includes('left')); assert.ok(awaitIndex >= 0); assert.equal(entry.script[awaitIndex + 1].command, 'EVENT_REMOVE_INPUT_SCRIPT'); assert.equal(entry.script[awaitIndex + 1].args.input.length, 8);
});

test('flat source backgrounds keep exact DMG colors and report shade underuse as an acknowledged warning', () => {
  const fixture = makeFixture({ scenes: { version: 2, startScene: 'opening', scenes: [{ id: 'opening', commands: [{ type: 'message', text: '単色背景です。' }] }] } }); const inspection = inspectGbStudioExport({ projectDir: fixture.root, settings: { warningsAcknowledged: true }, gbStudio: GB_STUDIO }); assert.equal(inspection.ok, true, JSON.stringify(inspection.errors)); assert.ok(inspection.warnings.some((entry) => entry.code === 'GBVN_DMG_SHADE_UNDERUSE'));
});

test('preflight blocks visual omissions and missing CDDA mapping without confirmation', () => {
  const fixture = makeFixture({ assets: [{ id: 'portrait', type: 'sprite', name: 'Portrait', source: 'assets/images/bg.png', options: { kind: 'sprite' } }, { id: 'cdda', type: 'cdda-track', name: 'CDDA', source: '', options: { track: 3, loop: true } }], scenes: { version: 2, startScene: 'opening', scenes: [{ id: 'opening', commands: [{ type: 'background', assetId: 'bg' }, { type: 'sprite', slot: 0, assetId: 'portrait', visible: true }, { type: 'audio', kind: 'cdda', action: 'play', assetId: 'cdda' }, { type: 'message', text: '停止確認' }] }] } });
  const inspection = inspectGbStudioExport({ projectDir: fixture.root, gbStudio: GB_STUDIO }); const codes = inspection.errors.map((entry) => entry.code); assert.ok(codes.includes('GBVN_VISUAL_OMISSION_REQUIRES_CONFIRMATION')); assert.ok(codes.includes('GBVN_CDDA_MAPPING_REQUIRED'));
});

test('CDDA accepts a validated external 4-channel MOD and stores a portable sidecar copy', () => {
  const fixture = makeFixture({ assets: [{ id: 'cdda', type: 'cdda-track', name: 'CDDA', source: '', options: { track: 3, loop: true } }], scenes: { version: 2, startScene: 'opening', scenes: [{ id: 'opening', commands: [{ type: 'background', assetId: 'bg' }, { type: 'audio', kind: 'cdda', action: 'play', assetId: 'cdda' }, { type: 'message', text: '外部MODです。' }] }] } }); const externalRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'pce-vn-external-mod-')); const modPath = path.join(externalRoot, 'replacement.mod'); fs.writeFileSync(modPath, convertPsgToMod(fixture.assets.assets.find((asset) => asset.id === 'song')).buffer);
  const inspection = inspectGbStudioExport({ projectDir: fixture.root, settings: { warningsAcknowledged: true, cddaMappings: { cdda: { type: 'external-mod', source: modPath } } }, gbStudio: GB_STUDIO }); assert.equal(inspection.ok, true, JSON.stringify(inspection.errors)); assert.equal(inspection.summary.musicTracks, 1); const outputDir = path.join(fixture.root, 'gb-output'); generateGbStudioProject({ inspection, outputDir }); const sidecar = JSON.parse(fs.readFileSync(path.join(fixture.root, 'assets', 'pce-vn-gb-studio-export.json'))); assert.match(sidecar.cddaMappings.cdda.source, /^assets\/music\/gb-studio-export\//); assert.ok(fs.existsSync(path.join(fixture.root, sidecar.cddaMappings.cdda.source))); assert.ok(fs.readdirSync(path.join(outputDir, 'assets', 'music', 'pce-vn')).some((name) => name.endsWith('.mod'))); const manifestText = fs.readFileSync(path.join(outputDir, MANIFEST_FILE), 'utf-8'); assert.equal(manifestText.includes(externalRoot), false);
});

test('generation refuses a non-owned non-empty output folder', () => {
  const fixture = makeFixture(); const inspection = inspectGbStudioExport({ projectDir: fixture.root, settings: { warningsAcknowledged: true }, gbStudio: GB_STUDIO }); const outputDir = path.join(fixture.root, 'foreign'); fs.mkdirSync(outputDir); fs.writeFileSync(path.join(outputDir, 'keep.txt'), 'user'); assert.throws(() => generateGbStudioProject({ inspection, outputDir }), (error) => error.code === 'GBVN_OUTPUT_NOT_OWNED'); assert.equal(fs.readFileSync(path.join(outputDir, 'keep.txt'), 'utf-8'), 'user');
});

test('regeneration backs up owned files and rejects a different source project identity', () => {
  const first = makeFixture(); const firstInspection = inspectGbStudioExport({ projectDir: first.root, settings: { warningsAcknowledged: true }, gbStudio: GB_STUDIO }); const outputDir = path.join(os.tmpdir(), `pce-vn-owned-output-${crypto.randomBytes(6).toString('hex')}`); generateGbStudioProject({ inspection: firstInspection, outputDir }); const regenerated = generateGbStudioProject({ inspection: firstInspection, outputDir }); assert.ok(regenerated.backupPath); assert.ok(fs.existsSync(path.join(regenerated.backupPath, MANIFEST_FILE))); const second = makeFixture(); const secondInspection = inspectGbStudioExport({ projectDir: second.root, settings: { warningsAcknowledged: true }, gbStudio: GB_STUDIO }); assert.throws(() => generateGbStudioProject({ inspection: secondInspection, outputDir }), (error) => error.code === 'GBVN_OUTPUT_NOT_OWNED');
});

test('CLI parses repeatable CDDA, external MOD, and audio substitution options', () => { const parsed = cli.parseArgs(['--project', 'p', '--out', 'o', '--gb-studio', 'g', '--cdda-map', 'cd=song', '--cdda-mod', 'intro=music.mod', '--audio-sub', 'voice=tone:660:0.1', '--confirm-visual-omissions', '--ack-warnings']); assert.equal(parsed.cddaMappings.cd, 'song'); assert.deepEqual(parsed.cddaMappings.intro, { type: 'external-mod', source: path.resolve('music.mod') }); assert.deepEqual(parsed.audioSubstitutions.voice, { type: 'tone', frequency: 660, duration: 0.1 }); assert.equal(parsed.visualOmissionsConfirmed, true); });

test('plugin manifest exposes only generic hooks/capabilities', () => { const manifest = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'plugins', 'pce-vn-gb-studio-exporter', 'manifest.json'))); assert.equal(manifest.version, '1.1.1'); assert.deepEqual(manifest.supportedCores, ['pc-engine']); assert.ok(manifest.renderer.capabilities.includes('novel-toolbar-action')); assert.ok(manifest.hooks.includes('inspectVnGbStudioExport')); });
