'use strict';

const assert = require('node:assert/strict');
const path = require('node:path');
const test = require('node:test');

const slideshow = require(path.join(__dirname, '..', 'plugins', 'slideshow', 'index.js'));

test('slideshow generator reads its bundled source template', () => {
  const source = slideshow.readTemplateSource();
  const result = slideshow.generateSource([
    { type: 'IMAGE', name: 'image001', sourcePath: 'gfx/image001.png' },
    { type: 'IMAGE', name: 'image002', sourcePath: 'gfx/image002.png' },
  ]);

  assert.match(source, /Generated by Slideshow Plugin v\{\{VERSION\}\}/);
  assert.match(source, /\{\{SLIDES_INIT\}\}/);
  assert.equal(result.ok, true);
  assert.match(result.sourceCode, /Generated by Slideshow Plugin v1\.0\.1/);
  assert.match(result.sourceCode, /#define SLIDE_COUNT\s+2/);
  assert.match(result.sourceCode, /&image001/);
  assert.match(result.sourceCode, /int main\(bool hardReset\)/);
});

test('slideshow build hook limits SGDK source scan to generated main.c', () => {
  const messages = [];
  const result = slideshow.onBuildStart(
    { projectDir: 'project' },
    { logger: { info: (message) => messages.push(message) } },
  );

  assert.equal(result.ok, true);
  assert.deepEqual(result.makeVariables, { SRC_C: 'src/main.c' });
  assert.match(messages[0], /build start/);
});

test('slideshow build log hook does not duplicate compiler errors', () => {
  const errors = [];
  const result = slideshow.onBuildLog(
    { level: 'error', line: 'src/main.c: error' },
    { logger: { error: (message) => errors.push(message) } },
  );

  assert.equal(result.ok, true);
  assert.deepEqual(errors, []);
});
