const PLUGIN_ID = 'pce-vn-gb-studio-exporter';
const DEFAULT_FONT = 'builtin:misaki-gothic-8x8';

function esc(value) { return String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]); }
function list(value) { return Array.isArray(value) ? value : []; }

export function activatePlugin({ plugin, api, logger, registerCapability }) {
  const invoke = async (hook, payload) => {
    const response = await api.plugins.invokeHook(plugin.id, hook, payload); if (!response?.ok) throw new Error(response?.error || `${hook}に失敗しました`); return response.result && typeof response.result === 'object' ? response.result : response;
  };

  const openExporter = ({ doc, assets, saveSnapshot } = {}) => new Promise((resolve) => {
    const modal = api.createModal({ id: `${plugin.id}-modal-${Date.now()}`, panelClassName: 'app-panel pce-gb-export-panel', labelledBy: 'pce-gb-export-title' });
    const state = { busy: false, gbStudioExecutable: '', outputDir: '', fontMode: 'builtin', fontPath: '', mode: 'generate', visualOmissionsConfirmed: false, warningsAcknowledged: false, cddaMappings: {}, audioSubstitutions: {}, inspection: null, status: '', statusLevel: '' }; let settled = false;
    const finish = (result) => { if (settled) return; settled = true; window.removeEventListener('keydown', onKeyDown); modal.close(); modal.destroy?.(); resolve(result); };
    const cancel = () => finish({ ok: false, canceled: true }); const onKeyDown = (event) => { if (event.key === 'Escape' && !state.busy) cancel(); };
    const settings = () => ({ font: state.fontMode === 'builtin' ? DEFAULT_FONT : state.fontPath, gbStudioExecutable: state.gbStudioExecutable, visualOmissionsConfirmed: state.visualOmissionsConfirmed, warningsAcknowledged: state.warningsAcknowledged, cddaMappings: state.cddaMappings, audioSubstitutions: state.audioSubstitutions });
    const payload = () => ({ doc, assets: { version: 2, assets: list(assets) }, settings: settings(), gbStudio: state.gbStudioExecutable });

    const diagnosticHtml = () => {
      if (!state.inspection) return '<p>設定後に「Preflight」を実行してください。</p>';
      const items = [...list(state.inspection.errors), ...list(state.inspection.warnings)]; if (!items.length) return '<p>変換を阻止する問題はありません。</p>';
      return items.map((item) => `<p class="pce-gb-export-diagnostic" data-severity="${esc(item.severity)}"><strong>${esc(item.code)}</strong> ${esc(item.location)} — ${esc(item.message)}</p>`).join('');
    };
    const mappingsHtml = () => {
      const requirements = state.inspection?.requirements; if (!requirements) return '';
      const songs = list(requirements.psgSongs); const cdda = list(requirements.cdda).map((requirement) => { const mapping = state.cddaMappings[requirement.id] || requirement.mapping || ''; const external = mapping?.type === 'external-mod'; const target = typeof mapping === 'string' ? mapping : mapping?.targetAssetId || ''; return `<label class="pce-gb-export-mapping"><span>CDDA: ${esc(requirement.name)} <code>${esc(requirement.id)}</code></span><span><select data-cdda="${esc(requirement.id)}"><option value="">代替を選択</option>${songs.map((song) => `<option value="${esc(song.id)}"${target === song.id ? ' selected' : ''}>${esc(song.name)} (${esc(song.id)})</option>`).join('')}<option value="__external__"${external ? ' selected' : ''}>外部4ch ProTracker MOD</option></select>${external ? ` <input value="${esc(mapping.source || '')}" readonly placeholder=".mod file"> <button type="button" class="btn-sm" data-pick-mod="${esc(requirement.id)}">MOD選択</button>` : ''}</span></label>`; }).join('');
      const substitutions = list(requirements.audioSubstitutions).map((requirement) => { const mapping = state.audioSubstitutions[requirement.id] || { type: 'tone', frequency: 440, duration: 0.08 }; return `<label class="pce-gb-export-mapping"><span>${esc(requirement.type)}: ${esc(requirement.name)} <code>${esc(requirement.id)}</code></span><span><select data-substitution="${esc(requirement.id)}"><option value="tone"${mapping.type !== 'omit' ? ' selected' : ''}>tone代替</option><option value="omit"${mapping.type === 'omit' ? ' selected' : ''}>明示省略</option></select> <input data-frequency="${esc(requirement.id)}" type="number" min="40" max="5000" value="${esc(mapping.frequency || 440)}" title="tone Hz"></span></label>`; }).join('');
      const voiceCount = list(requirements.automaticVoiceSubstitutions).length;
      return cdda || substitutions || voiceCount ? `<h3>音声mapping</h3><div class="pce-gb-export-mappings">${cdda}${substitutions}</div><p>message voice ${voiceCount}件は話者別の安定したtext toneへ自動置換し、監査fileへ全件保存します。</p>` : '';
    };
    const summaryHtml = () => { const summary = state.inspection?.summary; if (!summary) return ''; return `<div class="pce-gb-export-summary"><span>source scene ${summary.sourceScenes || 0}</span><span>output scene ${summary.outputScenes || 0}</span><span>BG ${summary.backgroundVariants || 0}×2</span><span>font ${summary.fontPages || 0} page</span><span>BGM ${summary.musicTracks || 0}</span></div>`; };

    const bind = () => {
      const panel = modal.panel; panel.querySelector('[data-action="cancel"]')?.addEventListener('click', cancel); panel.querySelector('[data-action="pick-gb"]')?.addEventListener('click', async () => { const picked = await api.electronAPI.pickFile({ title: 'GB Studio 4.3.1/4.3.2実行ファイル', properties: ['openFile'], filters: [{ name: 'Executable', extensions: ['exe'] }] }); const selected = picked?.sourcePath || picked?.filePath || picked?.filePaths?.[0] || ''; if (selected) { state.gbStudioExecutable = selected; state.inspection = null; render(); } });
      panel.querySelector('[data-action="pick-output"]')?.addEventListener('click', async () => { const picked = await api.electronAPI.pickFile({ title: 'GB Studio出力folder', properties: ['openDirectory'] }); const selected = picked?.sourcePath || picked?.filePath || picked?.filePaths?.[0] || ''; if (selected) { state.outputDir = selected; render(); } });
      panel.querySelector('[data-action="pick-font"]')?.addEventListener('click', async () => { const picked = await api.electronAPI.pickFile({ title: 'BDF / TTF / OTF font', properties: ['openFile'], filters: [{ name: 'Font', extensions: ['bdf', 'ttf', 'otf', 'ttc'] }] }); const selected = picked?.sourcePath || picked?.filePath || picked?.filePaths?.[0] || ''; if (selected) { state.fontPath = selected; state.fontMode = 'custom'; state.inspection = null; render(); } });
      panel.querySelector('[data-font-mode]')?.addEventListener('change', (event) => { state.fontMode = event.target.value; state.inspection = null; render(); }); panel.querySelector('[data-mode]')?.addEventListener('change', (event) => { state.mode = event.target.value; }); panel.querySelector('[data-visual-confirm]')?.addEventListener('change', (event) => { state.visualOmissionsConfirmed = event.target.checked; state.inspection = null; }); panel.querySelector('[data-warning-confirm]')?.addEventListener('change', (event) => { state.warningsAcknowledged = event.target.checked; });
      panel.querySelectorAll('[data-cdda]').forEach((select) => select.addEventListener('change', () => { const id = select.dataset.cdda; state.cddaMappings[id] = select.value === '__external__' ? (state.cddaMappings[id]?.type === 'external-mod' ? state.cddaMappings[id] : { type: 'external-mod', source: '' }) : select.value; state.inspection = null; render(); })); panel.querySelectorAll('[data-pick-mod]').forEach((button) => button.addEventListener('click', async () => { const picked = await api.electronAPI.pickFile({ title: 'GB Studio 4ch ProTracker MOD', properties: ['openFile'], filters: [{ name: 'ProTracker MOD', extensions: ['mod'] }] }); const selected = picked?.sourcePath || picked?.filePath || picked?.filePaths?.[0] || ''; if (selected) { state.cddaMappings[button.dataset.pickMod] = { type: 'external-mod', source: selected }; state.inspection = null; render(); } })); panel.querySelectorAll('[data-substitution]').forEach((select) => select.addEventListener('change', () => { const id = select.dataset.substitution; const frequency = [...panel.querySelectorAll('[data-frequency]')].find((input) => input.dataset.frequency === id); state.audioSubstitutions[id] = { type: select.value, frequency: Number(frequency?.value) || 440, duration: 0.08 }; state.inspection = null; })); panel.querySelectorAll('[data-frequency]').forEach((input) => input.addEventListener('change', () => { const id = input.dataset.frequency; state.audioSubstitutions[id] = { ...(state.audioSubstitutions[id] || { type: 'tone', duration: 0.08 }), frequency: Number(input.value) || 440 }; state.inspection = null; }));
      panel.querySelector('[data-action="inspect"]')?.addEventListener('click', () => void inspect()); panel.querySelector('[data-action="generate"]')?.addEventListener('click', () => void generate());
    };

    const render = () => {
      modal.panel.innerHTML = `<div class="page-header modal-header"><h2 id="pce-gb-export-title">GB Studio 4.3.1/4.3.2出力</h2><button class="icon-btn" type="button" data-action="cancel">✕</button></div><div class="settings-form compact-form"><div class="pce-gb-export-grid"><label>GB Studio</label><input value="${esc(state.gbStudioExecutable)}" readonly placeholder="gb-studio.exe"><button type="button" class="btn-sm" data-action="pick-gb">選択</button><label>出力folder</label><input value="${esc(state.outputDir)}" readonly placeholder="空folderまたはexporter生成folder"><button type="button" class="btn-sm" data-action="pick-output">選択</button><label>日本語font</label><select data-font-mode><option value="builtin"${state.fontMode === 'builtin' ? ' selected' : ''}>Misaki Gothic 8x8（推奨・組込）</option><option value="custom"${state.fontMode === 'custom' ? ' selected' : ''}>BDF / TTF / OTF / TTC</option></select><button type="button" class="btn-sm" data-action="pick-font"${state.fontMode !== 'custom' ? ' disabled' : ''}>font選択</button>${state.fontMode === 'custom' ? `<label>選択font</label><input value="${esc(state.fontPath)}" readonly><span></span>` : ''}<label>処理mode</label><select data-mode><option value="generate"${state.mode === 'generate' ? ' selected' : ''}>生成＋静的検証</option><option value="verify"${state.mode === 'verify' ? ' selected' : ''}>生成＋公式build成果物必須</option></select><span></span></div><div class="pce-gb-export-checks"><label><input type="checkbox" data-visual-confirm${state.visualOmissionsConfirmed ? ' checked' : ''}> Phase 1ではsprite/spritemove等の列挙済み視覚装飾を省略する</label><label><input type="checkbox" data-warning-confirm${state.warningsAcknowledged ? ' checked' : ''}> Preflight warningと曲別監査を確認した</label></div>${mappingsHtml()}${summaryHtml()}<div class="pce-gb-export-diagnostics">${diagnosticHtml()}</div><p class="form-hint ${esc(state.statusLevel)}">${esc(state.status)}</p><div class="form-actions-inline modal-actions-end"><button type="button" class="btn-sm" data-action="cancel"${state.busy ? ' disabled' : ''}>キャンセル</button><button type="button" class="btn-sm" data-action="inspect"${state.busy ? ' disabled' : ''}>Preflight</button><button type="button" class="btn-primary" data-action="generate"${state.busy || !state.inspection?.ok || !state.outputDir || !state.warningsAcknowledged ? ' disabled' : ''}>生成</button></div></div>`; bind();
    };

    const inspect = async () => {
      if (!state.gbStudioExecutable) { state.status = 'GB Studio 4.3.1または4.3.2を選択してください。'; state.statusLevel = 'error'; render(); return; } if (state.fontMode === 'custom' && !state.fontPath) { state.status = 'font fileを選択してください。'; state.statusLevel = 'error'; render(); return; }
      state.busy = true; state.status = 'BG量子化・font page・BGMをpreflight中…'; state.statusLevel = ''; render();
      try { const inspection = await invoke('inspectVnGbStudioExport', payload()); state.inspection = inspection; list(inspection.requirements?.cdda).forEach((requirement) => { if (!state.cddaMappings[requirement.id] && requirement.mapping) state.cddaMappings[requirement.id] = requirement.mapping; }); list(inspection.requirements?.audioSubstitutions).forEach((requirement) => { if (!state.audioSubstitutions[requirement.id]) state.audioSubstitutions[requirement.id] = requirement.mapping && typeof requirement.mapping === 'object' ? requirement.mapping : { type: 'tone', frequency: 440, duration: 0.08 }; }); state.status = inspection.ok ? `Preflight完了: warning ${inspection.warnings.length}件` : `Preflight停止: error ${inspection.errors.length}件`; state.statusLevel = inspection.ok ? 'info' : 'error'; }
      catch (error) { state.status = `Preflight失敗: ${error.message || error}`; state.statusLevel = 'error'; } finally { state.busy = false; render(); }
    };

    const generate = async () => {
      if (!state.outputDir) { state.status = '出力folderを選択してください。'; state.statusLevel = 'error'; render(); return; } state.busy = true; state.status = '最新設定で再preflight中…'; state.statusLevel = ''; render();
      try { const latest = await invoke('inspectVnGbStudioExport', payload()); state.inspection = latest; if (!latest.ok) throw new Error(`preflight error ${latest.errors.length}件`); state.status = 'GB Studio projectを生成中…'; render(); const result = await invoke('exportVnGbStudioProject', { ...payload(), outputDir: state.outputDir, mode: state.mode }); if (typeof saveSnapshot === 'function') await saveSnapshot(doc); logger?.info?.(`GB Studio projectを出力しました: ${result.outputDir}`); finish({ ok: true, message: `GB Studio projectを出力しました: ${result.outputDir}`, result }); }
      catch (error) { state.status = `生成失敗: ${error.message || error}`; state.statusLevel = 'error'; logger?.error?.(state.status); state.busy = false; render(); }
    };

    window.addEventListener('keydown', onKeyDown); render(); modal.open();
  });

  const run = async (editor = {}) => { if (typeof editor.getSnapshot !== 'function') throw new Error('Novel editor action APIが不足しています'); const doc = await editor.getSnapshot(); const assets = typeof editor.getAssets === 'function' ? await editor.getAssets() : []; return openExporter({ doc, assets, saveSnapshot: editor.saveSnapshot }); };
  registerCapability('vn-gb-studio-exporter', { pluginId: plugin.id, label: 'GB Studio出力', openExporter });
  registerCapability('novel-toolbar-action', { id: 'gb-studio-export', pluginId: plugin.id, label: 'GB Studio出力', title: 'GB/GBC両対応のGB Studio 4.3.1/4.3.2 projectへ変換', priority: 100, order: 30, placement: 'after-preview', run });
}
