const PLUGIN_ID = 'pce-vn-gb-studio-exporter';
const DEFAULT_FONT = 'builtin:misaki-gothic-8x8';
const MUSIC_TARGETS = ['auto', 'pulse1', 'pulse2', 'wave', 'noise', 'mute'];

function esc(value) { return String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]); }
function list(value) { return Array.isArray(value) ? value : []; }
function copy(value) { return JSON.parse(JSON.stringify(value || {})); }
function clamp(value, min, max, fallback) { const parsed = Number(value); return Number.isFinite(parsed) ? Math.max(min, Math.min(max, parsed)) : fallback; }
function defaultMusicSetting() { return { tempoScale: 100, channels: Array.from({ length: 6 }, () => ({ target: 'auto', instrument: 'auto', volumeScale: 100, transpose: 0, priority: 50 })) }; }
function defaultBackgroundSetting() { return { brightness: 0, saturation: 100, gbcDither: false, dmgDither: false, focusX: 0.5, focusY: 0.5 }; }
function defaultSpriteSetting() { return { crop: null, scale: 100, offsetX: 0, offsetY: 0, brightness: 0, saturation: 100, gbcDither: false, dmgDither: false, sourceHash: '' }; }

export function activatePlugin({ plugin, api, logger, registerCapability }) {
  const invoke = async (hook, payload) => {
    const response = await api.plugins.invokeHook(plugin.id, hook, payload);
    if (!response?.ok) { const error = new Error(response?.error || `${hook}に失敗しました`); error.code = response?.code || ''; throw error; }
    return response.result && typeof response.result === 'object' ? response.result : response;
  };

  const openExporter = async ({ doc, assets, saveSnapshot } = {}) => {
    let projectConfig = {}; let projectConfigError = '';
    try { projectConfig = await api.electronAPI.getProjectConfig?.() || {}; } catch (error) { projectConfigError = `プロジェクト設定の読み込みに失敗しました: ${error?.message || error}`; }
    const savedGbStudioExecutable = String(projectConfig?.pluginSettings?.[PLUGIN_ID]?.gbStudioExecutable || '').trim();
    return new Promise((resolve) => {
      const modal = api.createModal({ id: `${plugin.id}-modal-${Date.now()}`, panelClassName: 'app-panel pce-gb-export-panel', labelledBy: 'pce-gb-export-title' });
      const state = { busy: false, previewBusy: false, view: 'main', gbStudioExecutable: savedGbStudioExecutable, outputDir: '', fontMode: 'builtin', fontPath: '', mode: 'generate', portraitRenderMode: 'baked', portraitModeExplicit: false, visualOmissionsConfirmed: false, warningsAcknowledged: false, cddaMappings: {}, audioSubstitutions: {}, music: {}, backgrounds: {}, sprites: {}, spriteClipboard: null, settingsLoaded: false, inspection: null, inspectionStale: false, selectedMusic: '', selectedBackground: '', selectedBackgroundFullScreen: false, selectedSprite: '', selectedSpriteScene: '', selectedSpriteAnimation: '', backgroundMode: 'gbc', spriteMode: 'gbc', musicPreview: null, backgroundPreview: null, spritePreview: null, spritePlaying: false, spriteFrame: 0, spriteLoop: true, previewError: '', previewLoop: true, status: projectConfigError, statusLevel: projectConfigError ? 'error' : '' };
      const timers = { music: 0, background: 0, sprite: 0, spritePlayback: 0 }; const epochs = { music: 0, background: 0, sprite: 0 }; const audio = { context: null, timer: 0, oscillators: [] }; let settled = false;
      const stopAudio = () => { if (audio.timer) window.clearTimeout(audio.timer); audio.timer = 0; audio.oscillators.forEach((oscillator) => { try { oscillator.stop(); } catch (_) {} }); audio.oscillators = []; if (audio.context) void audio.context.close().catch(() => {}); audio.context = null; };
      const stopSpriteAnimation = () => { window.clearTimeout(timers.spritePlayback); timers.spritePlayback = 0; state.spritePlaying = false; };
      const finish = (result) => { if (settled) return; settled = true; window.clearTimeout(timers.music); window.clearTimeout(timers.background); window.clearTimeout(timers.sprite); stopSpriteAnimation(); stopAudio(); window.removeEventListener('keydown', onKeyDown); modal.close(); modal.destroy?.(); resolve(result); };
      const cancel = () => finish({ ok: false, canceled: true });
      const onKeyDown = (event) => { if (event.key !== 'Escape' || state.busy) return; if (state.view !== 'main') { stopAudio(); state.view = 'main'; render(); } else cancel(); };
      const ensureMusic = (id, seed) => { if (!id) return defaultMusicSetting(); if (!state.music[id]) { const base = seed || {}; state.music[id] = { tempoScale: clamp(base.tempoScale, 50, 200, 100), channels: Array.from({ length: 6 }, (_, index) => ({ ...defaultMusicSetting().channels[index], ...(base.channels?.[index] || {}) })) }; } return state.music[id]; };
      const ensureBackground = (id, seed) => { if (!id) return defaultBackgroundSetting(); if (!state.backgrounds[id]) state.backgrounds[id] = { ...defaultBackgroundSetting(), ...(seed || {}) }; return state.backgrounds[id]; };
      const ensureSprite = (id, seed) => { if (!id) return defaultSpriteSetting(); if (!state.sprites[id]) state.sprites[id] = { ...defaultSpriteSetting(), ...(seed || {}), crop: seed?.crop ? { ...seed.crop } : null }; return state.sprites[id]; };
      const settings = () => { const output = { font: state.fontMode === 'builtin' ? DEFAULT_FONT : state.fontPath, gbStudioExecutable: state.gbStudioExecutable, visualOmissionsConfirmed: state.visualOmissionsConfirmed, warningsAcknowledged: state.warningsAcknowledged, cddaMappings: copy(state.cddaMappings), audioSubstitutions: copy(state.audioSubstitutions), music: copy(state.music), backgrounds: copy(state.backgrounds), sprites: copy(state.sprites) }; if (state.settingsLoaded || state.portraitModeExplicit) output.portraitRenderMode = state.portraitRenderMode; return output; };
      const payload = () => ({ doc, assets: { version: 2, assets: list(assets) }, settings: settings(), gbStudio: state.gbStudioExecutable });
      const previewPayload = () => ({ assets: { version: 2, assets: list(assets) } });
      const markAdjusted = () => { state.inspectionStale = true; state.visualOmissionsConfirmed = false; state.warningsAcknowledged = false; state.status = '調整値を変更しました。生成前にPreflightを再実行してください。'; state.statusLevel = 'info'; };
      const saveGbStudioExecutable = async (executablePath) => {
        const latestConfig = await api.electronAPI.getProjectConfig?.() || projectConfig || {}; const pluginSettings = latestConfig.pluginSettings && typeof latestConfig.pluginSettings === 'object' ? latestConfig.pluginSettings : {}; const current = pluginSettings[PLUGIN_ID] && typeof pluginSettings[PLUGIN_ID] === 'object' ? pluginSettings[PLUGIN_ID] : {};
        const result = await api.electronAPI.saveProjectConfig({ pluginSettings: { ...pluginSettings, [PLUGIN_ID]: { ...current, gbStudioExecutable: executablePath } } });
        if (!result?.ok) throw new Error(result?.error || 'プロジェクト設定を保存できませんでした'); projectConfig = result.config || latestConfig;
      };

      const playPreview = async (preview) => {
        stopAudio(); if (!preview?.rows?.length) return; const Audio = window.AudioContext || window.webkitAudioContext; if (!Audio) { state.previewError = 'この環境ではWebAudio previewを利用できません。'; render(); return; }
        const context = new Audio(); audio.context = context; await context.resume(); let step = 0; const rowSeconds = Math.max(0.025, Math.min(0.3, 15 / Math.max(30, Number(preview.bpm) || 120)));
        const tick = () => {
          if (audio.context !== context) return; audio.oscillators = []; const row = preview.rows[step] || [];
          row.forEach((cell) => { if (!(cell.volume > 0) || !(cell.frequency > 0)) return; const oscillator = context.createOscillator(); const gain = context.createGain(); oscillator.type = ['sine', 'square', 'triangle', 'sawtooth'].includes(cell.waveform) ? cell.waveform : 'square'; oscillator.frequency.value = Math.max(20, Math.min(8000, Number(cell.frequency) || 220)); gain.gain.value = Math.max(0.002, Math.min(0.08, Number(cell.volume) / 31 * 0.08)); oscillator.connect(gain).connect(context.destination); oscillator.start(); oscillator.stop(context.currentTime + rowSeconds * 0.92); audio.oscillators.push(oscillator); });
          step += 1; if (step >= preview.rows.length) { if (state.previewLoop || preview.loop) step = Math.max(0, Math.min(preview.rows.length - 1, Number(preview.loopPoint) || 0)); else { stopAudio(); return; } } audio.timer = window.setTimeout(tick, rowSeconds * 1000);
        };
        tick();
      };

      const scheduleMusicPreview = () => {
        window.clearTimeout(timers.music); const id = state.selectedMusic; if (!id) return; const generation = ++epochs.music; state.previewBusy = true; state.previewError = '';
        timers.music = window.setTimeout(async () => { try { const result = await invoke('previewVnGbStudioMusic', { ...previewPayload(), assetId: id, settings: { music: { [id]: ensureMusic(id) } }, generation }); if (generation !== epochs.music || result.generation !== generation) return; state.musicPreview = result; } catch (error) { if (generation === epochs.music) state.previewError = `BGM preview失敗: ${error.message || error}`; } finally { if (generation === epochs.music) { state.previewBusy = false; render(); } } }, 200);
      };
      const scheduleBackgroundPreview = () => {
       window.clearTimeout(timers.background); const id = state.selectedBackground; if (!id) return; const generation = ++epochs.background; state.previewBusy = true; state.previewError = '';
       timers.background = window.setTimeout(async () => { try { const result = await invoke('previewVnGbStudioBackground', { ...previewPayload(), assetId: id, fullScreen: state.selectedBackgroundFullScreen, settings: { backgrounds: { [id]: ensureBackground(id) } }, generation }); if (generation !== epochs.background || result.generation !== generation) return; state.backgroundPreview = result; } catch (error) { if (generation === epochs.background) state.previewError = `画像preview失敗: ${error.message || error}`; } finally { if (generation === epochs.background) { state.previewBusy = false; render(); } } }, 200);
     };
      const diagnosticHtml = () => {
        if (!state.inspection) return '<p>設定後に「Preflight」を実行してください。</p>';
        const items = [...list(state.inspection.errors), ...list(state.inspection.warnings)];
        if (!items.length) return '<p>変換を阻止する問題はありません。</p>';
        return items.map((item) => `<p class="pce-gb-export-diagnostic" data-severity="${esc(item.severity)}"><strong>${esc(item.code)}</strong> ${esc(item.location)} — ${esc(item.message)}</p>`).join('');
      };
      const scheduleSpritePreview = () => {
        window.clearTimeout(timers.sprite); stopSpriteAnimation(); const id = state.selectedSprite; if (!id) return; const generation = ++epochs.sprite; state.previewBusy = true; state.previewError = '';
        timers.sprite = window.setTimeout(async () => { try { const result = await invoke('previewVnGbStudioSprite', { ...previewPayload(), assetId: id, settings: { backgrounds: copy(state.backgrounds), sprites: { [id]: ensureSprite(id) } }, renderMode: state.portraitRenderMode, mode: state.spriteMode, usageSceneId: state.selectedSpriteScene, animationId: state.selectedSpriteAnimation, generation }); if (generation !== epochs.sprite || result.generation !== generation) return; state.spritePreview = result; state.selectedSpriteAnimation = result.animationId; state.spriteFrame = 0; } catch (error) { if (generation === epochs.sprite) state.previewError = `立ち絵preview失敗: ${error.message || error}`; } finally { if (generation === epochs.sprite) { state.previewBusy = false; render(); } } }, 200);
      };
      const scheduleSpritePlayback = () => {
        window.clearTimeout(timers.spritePlayback); if (!state.spritePlaying) return; const frames = list(state.spritePreview?.images?.frames); const delays = list(state.spritePreview?.animation?.frameDelays); if (frames.length < 2) { state.spritePlaying = false; render(); return; } const delay = Math.max(1, Number(delays[state.spriteFrame]) || 1);
        timers.spritePlayback = window.setTimeout(() => { const next = state.spriteFrame + 1; if (next >= frames.length && !state.spriteLoop) { state.spriteFrame = frames.length - 1; state.spritePlaying = false; render(); return; } state.spriteFrame = next % frames.length; render(); scheduleSpritePlayback(); }, delay * 1000 / 60);
      };
      const mappingsHtml = () => {
        const requirements = state.inspection?.requirements; if (!requirements) return ''; const songs = list(requirements.psgSongs);
        const cdda = list(requirements.cdda).map((requirement) => {
          const mapping = state.cddaMappings[requirement.id] || requirement.mapping || ''; const external = mapping?.type === 'external-mod'; const target = typeof mapping === 'string' ? mapping : mapping?.targetAssetId || '';
          return `<label class="pce-gb-export-mapping"><span>CDDA: ${esc(requirement.name)} <code>${esc(requirement.id)}</code></span><span><select data-cdda="${esc(requirement.id)}"><option value="">代替を選択</option>${songs.map((song) => `<option value="${esc(song.id)}"${target === song.id ? ' selected' : ''}>${esc(song.name)} (${esc(song.id)})</option>`).join('')}<option value="__external__"${external ? ' selected' : ''}>外部4ch ProTracker MOD</option></select>${external ? ` <input value="${esc(mapping.source || '')}" readonly> <button type="button" class="btn-sm" data-pick-mod="${esc(requirement.id)}">MOD選択</button>` : ''}</span></label>`;
        }).join('');
        const substitutions = list(requirements.audioSubstitutions).map((requirement) => {
          const mapping = state.audioSubstitutions[requirement.id] || { type: 'tone', frequency: 440, duration: 0.08 };
          return `<label class="pce-gb-export-mapping"><span>${esc(requirement.type)}: ${esc(requirement.name)}</span><span><select data-substitution="${esc(requirement.id)}"><option value="tone"${mapping.type !== 'omit' ? ' selected' : ''}>tone代替</option><option value="omit"${mapping.type === 'omit' ? ' selected' : ''}>明示省略</option></select> <input data-frequency="${esc(requirement.id)}" type="number" min="40" max="5000" value="${esc(mapping.frequency || 440)}"></span></label>`;
        }).join('');
        const voiceCount = list(requirements.automaticVoiceSubstitutions).length;
        return cdda || substitutions || voiceCount ? `<h3>音声mapping</h3><div class="pce-gb-export-mappings">${cdda}${substitutions}</div><p>message voice ${voiceCount}件は話者別text toneへ自動置換して監査します。</p>` : '';
      };
      const summaryHtml = () => {
        const summary = state.inspection?.summary; if (!summary) return ''; const choices = summary.choices || {};
        return `<div class="pce-gb-export-summary"><span>source scene ${summary.sourceScenes || 0}</span><span>output scene ${summary.outputScenes || 0}</span><span>choice 2/3/4 = ${choices[2] || 0}/${choices[3] || 0}/${choices[4] || 0}</span><span>到達不能 ${summary.unreachableBlocks || 0}</span><span>BG ${summary.backgroundVariants || 0}×2</span><span>立ち絵 ${summary.spriteAssets || 0} / ${esc(summary.portraitRenderMode || state.portraitRenderMode)}</span><span>visual timeline ${summary.visualTimelines || 0}</span><span>font ${summary.fontPages || 0} page</span><span>BGM ${summary.musicTracks || 0}</span></div>`;
      };

      const musicHtml = () => {
        const catalog = list(state.inspection?.requirements?.psgSongs);
        if (!state.selectedMusic && catalog.length) state.selectedMusic = catalog[0].id;
        const selected = catalog.find((item) => item.id === state.selectedMusic) || catalog[0]; const setting = ensureMusic(selected?.id, selected?.settings); const audit = state.musicPreview?.audit; const assignments = new Map(list(audit?.channelAssignments).map((item) => [item.sourceChannel, item]));
        const rows = Array.from({ length: 6 }, (_, channel) => {
          const current = setting.channels[channel]; const auto = assignments.get(channel);
          const instruments = [`<option value="auto"${current.instrument === 'auto' ? ' selected' : ''}>auto</option>`, ...Array.from({ length: 31 }, (_, index) => `<option value="${index + 1}"${Number(current.instrument) === index + 1 ? ' selected' : ''}>${index + 1}</option>`)].join('');
          return `<tr><td>CH${channel + 1}</td><td><select data-music-channel="${channel}" data-field="target">${MUSIC_TARGETS.map((target) => `<option value="${target}"${current.target === target ? ' selected' : ''}>${target}</option>`).join('')}</select><small>${esc(auto ? `→ ${auto.target} / ${auto.family}` : '')}</small></td><td><select data-music-channel="${channel}" data-field="instrument">${instruments}</select></td><td><input type="number" min="0" max="200" value="${esc(current.volumeScale)}" data-music-channel="${channel}" data-field="volumeScale"></td><td><input type="number" min="-24" max="24" value="${esc(current.transpose)}" data-music-channel="${channel}" data-field="transpose"></td><td><input type="number" min="0" max="100" value="${esc(current.priority)}" data-music-channel="${channel}" data-field="priority"></td></tr>`;
        }).join('');
        return `<div class="page-header modal-header"><h2 id="pce-gb-export-title">BGM調整（WebAudio近似preview）</h2><button class="icon-btn" type="button" data-action="back">←</button></div>
          <div class="pce-gb-adjust-toolbar"><label>曲 <select data-music-asset>${catalog.map((item) => `<option value="${esc(item.id)}"${item.id === selected?.id ? ' selected' : ''}>${esc(item.name)} (${esc(item.id)})</option>`).join('')}</select></label><span class="pce-gb-audit-badge" data-status="${esc(audit?.status || selected?.auditStatus || 'pending')}">${esc(audit?.status || selected?.auditStatus || '未preview')}</span><button type="button" class="btn-sm" data-action="reset-music">この曲をreset</button><button type="button" class="btn-sm" data-action="reset-all-music">全曲reset</button></div>
          <label class="pce-gb-slider-row"><span>tempo</span><input type="range" min="50" max="200" value="${esc(setting.tempoScale)}" data-music-tempo><input type="number" min="50" max="200" value="${esc(setting.tempoScale)}" data-music-tempo-number><span>%</span></label>
          <div class="pce-gb-table-wrap"><table class="pce-gb-channel-table"><thead><tr><th>PCE</th><th>target / auto結果</th><th>instrument</th><th>volume %</th><th>transpose</th><th>priority</th></tr></thead><tbody>${rows}</tbody></table></div>
          <div class="pce-gb-preview-controls"><button type="button" class="btn-sm" data-play="source">Source A</button><button type="button" class="btn-sm" data-play="gb">GB近似 B</button><button type="button" class="btn-sm" data-action="stop-audio">停止</button><label><input type="checkbox" data-preview-loop${state.previewLoop ? ' checked' : ''}> loop</label><span>${state.previewBusy ? 'preview生成中…' : ''}</span></div>
          <p class="form-hint">WebAudioは調整用近似です。最終判定はGB Studio公式ROMで行います。</p><p class="form-hint error">${esc(state.previewError)}</p>`;
      };

      const backgroundHtml = () => {
        const catalog = list(state.inspection?.requirements?.backgrounds);
        if (!state.selectedBackground && catalog.length) state.selectedBackground = catalog[0].id;
        const selected = catalog.find((item) => item.id === state.selectedBackground) || catalog[0]; const setting = ensureBackground(selected?.id, selected?.settings); const variants = list(selected?.variants);
        if (variants.length && !variants.some((variant) => Boolean(variant.fullScreen) === state.selectedBackgroundFullScreen)) state.selectedBackgroundFullScreen = Boolean(variants[0].fullScreen);
        const preview = state.backgroundPreview; const converted = preview?.images?.[state.backgroundMode]; const metric = state.backgroundMode === 'gbc' ? preview?.audit?.gbc : preview?.audit?.dmg;
        return `<div class="page-header modal-header"><h2 id="pce-gb-export-title">画像調整</h2><button class="icon-btn" type="button" data-action="back">←</button></div>
          <div class="pce-gb-adjust-toolbar"><label>画像 <select data-background-asset>${catalog.map((item) => `<option value="${esc(item.id)}"${item.id === selected?.id ? ' selected' : ''}>${esc(item.name)} (${esc(item.id)})</option>`).join('')}</select></label>${variants.length > 1 ? `<label>variant <select data-background-variant>${variants.map((variant) => `<option value="${variant.fullScreen ? 1 : 0}"${Boolean(variant.fullScreen) === state.selectedBackgroundFullScreen ? ' selected' : ''}>${variant.fullScreen ? 'full screen' : 'dialogue'}</option>`).join('')}</select></label>` : ''}<label>出力 <select data-background-mode><option value="gbc"${state.backgroundMode === 'gbc' ? ' selected' : ''}>GBC</option><option value="dmg"${state.backgroundMode === 'dmg' ? ' selected' : ''}>DMG</option></select></label><button type="button" class="btn-sm" data-action="reset-background">この画像をreset</button><button type="button" class="btn-sm" data-action="reset-all-backgrounds">全画像reset</button></div>
          <div class="pce-gb-image-compare"><figure><figcaption>元画像</figcaption>${preview?.images?.source ? `<img loading="lazy" src="${preview.images.source}" alt="元画像">` : '<div class="pce-gb-preview-placeholder">選択時に遅延読込</div>'}</figure><figure><figcaption>変換後 ${state.backgroundMode.toUpperCase()}</figcaption>${converted ? `<img src="${converted}" alt="変換後">` : '<div class="pce-gb-preview-placeholder">preview生成中</div>'}</figure></div>
          <div class="pce-gb-image-controls"><label class="pce-gb-slider-row"><span>明るさ</span><input type="range" min="-100" max="100" value="${esc(setting.brightness)}" data-background-field="brightness"><input type="number" min="-100" max="100" value="${esc(setting.brightness)}" data-background-number="brightness"></label><label class="pce-gb-slider-row"><span>彩度</span><input type="range" min="0" max="200" value="${esc(setting.saturation)}" data-background-field="saturation"><input type="number" min="0" max="200" value="${esc(setting.saturation)}" data-background-number="saturation"><span>%</span></label><label><input type="checkbox" data-background-dither="gbcDither"${setting.gbcDither ? ' checked' : ''}> GBC 4×4 ordered Bayer dither</label><label><input type="checkbox" data-background-dither="dmgDither"${setting.dmgDither ? ' checked' : ''}> DMG 4×4 ordered Bayer dither</label></div>
         <div class="pce-gb-export-summary"><span>palette ${metric?.palettes ?? '-'} / 7</span><span>tile ${metric?.uniqueTiles ?? '-'} / ${state.backgroundMode === 'dmg' ? 192 : '監査'}</span><span>hash ${esc(preview?.hashes?.[state.backgroundMode]?.slice(0, 12) || '-')}</span></div><p class="form-hint">補正とditherはartwork領域だけに適用し、dialogue matteは変更しません。</p><p class="form-hint error">${esc(state.previewError)}</p>`;
     };
      const spriteHtml = () => {
        const catalog = list(state.inspection?.requirements?.sprites); if (!state.selectedSprite && catalog.length) state.selectedSprite = catalog[0].id; const selected = catalog.find((item) => item.id === state.selectedSprite) || catalog[0]; const setting = ensureSprite(selected?.id, selected?.settings); const scenes = list(selected?.usageSceneIds); const animations = list(selected?.animations);
        if (scenes.length && !scenes.includes(state.selectedSpriteScene)) state.selectedSpriteScene = scenes[0]; if (animations.length && !animations.some((entry) => entry.id === state.selectedSpriteAnimation)) state.selectedSpriteAnimation = animations[0].id;
        const preview = state.spritePreview; const crop = setting.crop || preview?.crop || { x: 0, y: 0, width: preview?.audit?.crop?.width || 1, height: preview?.audit?.crop?.height || 1 }; const frames = list(preview?.images?.frames); const frameIndex = Math.max(0, Math.min(frames.length - 1, state.spriteFrame)); const converted = frames[frameIndex] || preview?.images?.frame; const metrics = state.spriteMode === 'gbc' ? preview?.audit?.gbc || selected?.metrics?.gbc : preview?.audit?.dmg || selected?.metrics?.dmg; const stale = Boolean(preview?.stale || selected?.stale);
        const cropField = (field, label, max = 4096) => `<label><span>${label}</span><input type="number" min="0" max="${max}" value="${esc(crop[field])}" data-sprite-crop="${field}"></label>`;
        return `<div class="page-header modal-header"><h2 id="pce-gb-export-title">立ち絵調整（${state.portraitRenderMode === 'actor' ? 'sprite actor' : '背景焼き込み'}）</h2><button class="icon-btn" type="button" data-action="back">←</button></div>
          <div class="pce-gb-adjust-toolbar"><label>asset <select data-sprite-asset>${catalog.map((item) => `<option value="${esc(item.id)}"${item.id === selected?.id ? ' selected' : ''}>${esc(item.name)} (${esc(item.id)})</option>`).join('')}</select></label>${scenes.length ? `<label>使用scene <select data-sprite-scene>${scenes.map((sceneId) => `<option value="${esc(sceneId)}"${sceneId === state.selectedSpriteScene ? ' selected' : ''}>${esc(sceneId)}</option>`).join('')}</select></label>` : ''}<label>animation <select data-sprite-animation>${animations.map((animation) => `<option value="${esc(animation.id)}"${animation.id === state.selectedSpriteAnimation ? ' selected' : ''}>${esc(animation.name || animation.id)} (${animation.frameCount}f${animation.loop ? ' loop' : ''})</option>`).join('')}</select></label><label>出力 <select data-sprite-mode><option value="gbc"${state.spriteMode === 'gbc' ? ' selected' : ''}>GBC</option><option value="dmg"${state.spriteMode === 'dmg' ? ' selected' : ''}>DMG</option></select></label></div>
          <div class="pce-gb-adjust-toolbar"><button type="button" class="btn-sm" data-action="copy-sprite">設定copy</button><button type="button" class="btn-sm" data-action="paste-sprite"${state.spriteClipboard ? '' : ' disabled'}>選択assetへpaste</button><button type="button" class="btn-sm" data-action="reset-sprite">このassetをreset</button><button type="button" class="btn-sm" data-action="reset-all-sprites">全asset reset</button><span class="pce-gb-audit-badge" data-status="${stale ? 'warning' : 'exact'}">${stale ? 'source変更あり' : 'source一致'}</span></div>
          <div class="pce-gb-image-compare pce-gb-sprite-compare"><figure><figcaption>元画像</figcaption>${preview?.images?.source ? `<img loading="lazy" src="${preview.images.source}" alt="元立ち絵">` : '<div class="pce-gb-preview-placeholder">選択時に遅延読込</div>'}</figure><figure><figcaption>変換後 ${state.spriteMode.toUpperCase()} frame ${frames.length ? frameIndex + 1 : 0}/${frames.length}</figcaption>${converted ? `<img src="${converted}" alt="変換後立ち絵">` : '<div class="pce-gb-preview-placeholder">preview生成中</div>'}</figure></div>
          <div class="pce-gb-preview-controls"><button type="button" class="btn-sm" data-action="play-sprite"${frames.length < 2 || state.spritePlaying ? ' disabled' : ''}>再生</button><button type="button" class="btn-sm" data-action="stop-sprite"${!state.spritePlaying ? ' disabled' : ''}>停止</button><label><input type="checkbox" data-sprite-loop${state.spriteLoop ? ' checked' : ''}> loop</label><span>${state.previewBusy ? 'preview生成中…' : ''}</span></div>
          <div class="pce-gb-sprite-crop"><strong>共通crop</strong>${cropField('x', 'X')}${cropField('y', 'Y')}${cropField('width', '幅')}${cropField('height', '高さ')}</div>
          <div class="pce-gb-image-controls"><label class="pce-gb-slider-row"><span>scale</span><input type="range" min="25" max="200" value="${esc(setting.scale)}" data-sprite-field="scale"><input type="number" min="25" max="200" value="${esc(setting.scale)}" data-sprite-number="scale"><span>%</span></label><label class="pce-gb-slider-row"><span>offset X</span><input type="range" min="-320" max="320" value="${esc(setting.offsetX)}" data-sprite-field="offsetX"><input type="number" min="-320" max="320" value="${esc(setting.offsetX)}" data-sprite-number="offsetX"></label><label class="pce-gb-slider-row"><span>offset Y</span><input type="range" min="-224" max="224" value="${esc(setting.offsetY)}" data-sprite-field="offsetY"><input type="number" min="-224" max="224" value="${esc(setting.offsetY)}" data-sprite-number="offsetY"></label><label class="pce-gb-slider-row"><span>明るさ</span><input type="range" min="-100" max="100" value="${esc(setting.brightness)}" data-sprite-field="brightness"><input type="number" min="-100" max="100" value="${esc(setting.brightness)}" data-sprite-number="brightness"></label><label class="pce-gb-slider-row"><span>彩度</span><input type="range" min="0" max="200" value="${esc(setting.saturation)}" data-sprite-field="saturation"><input type="number" min="0" max="200" value="${esc(setting.saturation)}" data-sprite-number="saturation"><span>%</span></label><label><input type="checkbox" data-sprite-dither="gbcDither"${setting.gbcDither ? ' checked' : ''}> GBC 4×4 ordered Bayer dither</label><label><input type="checkbox" data-sprite-dither="dmgDither"${setting.dmgDither ? ' checked' : ''}> DMG 4×4 ordered Bayer dither</label></div>
          <div class="pce-gb-export-summary"><span>OBJ ${metrics?.maxObjects ?? '-'} / 40</span><span>scanline OBJ ${metrics?.maxScanlineObjects ?? '-'} / 10</span><span>${state.portraitRenderMode === 'baked' ? '合成tileはPreflight監査' : '40×48 / inner 38×46'}</span><span>hash ${esc(preview?.hashes?.[state.spriteMode]?.slice(0, 12) || '-')}</span></div><p class="form-hint">cropは全animation frame共通です。actor modeの2人組OBJ制約とbaked modeのtile予算はPreflightで到達可能状態ごとに検査します。</p><p class="form-hint error">${esc(state.previewError)}</p>`;
      };
      const mainHtml = () => { const visualOmissions = list(state.inspection?.audits?.visual?.omissions); const needsVisualConfirmation = visualOmissions.length > 0; const needsWarningConfirmation = list(state.inspection?.warnings).length > 0; return `<div class="page-header modal-header"><h2 id="pce-gb-export-title">GB Studio 4.3.1/4.3.2出力</h2><button class="icon-btn" type="button" data-action="cancel">✕</button></div><div class="settings-form compact-form">
        <div class="pce-gb-export-grid"><label>GB Studio</label><input value="${esc(state.gbStudioExecutable)}" readonly placeholder="gb-studio.exe"><button type="button" class="btn-sm" data-action="pick-gb">選択</button><label>出力folder</label><input value="${esc(state.outputDir)}" readonly placeholder="空folderまたはexporter生成folder"><button type="button" class="btn-sm" data-action="pick-output">選択</button><label>日本語font</label><select data-font-mode><option value="builtin"${state.fontMode === 'builtin' ? ' selected' : ''}>Misaki Gothic 8x8（推奨・組込）</option><option value="custom"${state.fontMode === 'custom' ? ' selected' : ''}>BDF / TTF / OTF / TTC</option></select><button type="button" class="btn-sm" data-action="pick-font"${state.fontMode !== 'custom' ? ' disabled' : ''}>font選択</button>${state.fontMode === 'custom' ? `<label>選択font</label><input value="${esc(state.fontPath)}" readonly><span></span>` : ''}<label>立ち絵mode</label><select data-portrait-mode><option value="baked"${state.portraitRenderMode === 'baked' ? ' selected' : ''}>背景焼き込み（既定・最大4slot）</option><option value="actor"${state.portraitRenderMode === 'actor' ? ' selected' : ''}>sprite actor（最大2人）</option></select><span></span><label>処理mode</label><select data-mode><option value="generate"${state.mode === 'generate' ? ' selected' : ''}>生成＋静的検証</option><option value="verify"${state.mode === 'verify' ? ' selected' : ''}>生成＋公式build成果物必須</option></select><span></span></div>
        <div class="pce-gb-export-checks"><label><input type="checkbox" data-visual-confirm${state.visualOmissionsConfirmed ? ' checked' : ''}${needsVisualConfirmation ? '' : ' disabled'}> visual-auditの属性省略を確認した${needsVisualConfirmation ? `（${visualOmissions.length}件）` : '（省略なし）'}</label><label><input type="checkbox" data-warning-confirm${state.warningsAcknowledged ? ' checked' : ''}${needsWarningConfirmation ? '' : ' disabled'}> Preflight warningと音楽・画像・visual監査を確認した${needsWarningConfirmation ? `（${list(state.inspection?.warnings).length}件）` : '（warningなし）'}</label></div>
        <div class="pce-gb-adjust-launch"><button type="button" class="btn-sm" data-action="music-adjust"${!list(state.inspection?.requirements?.psgSongs).length ? ' disabled' : ''}>BGM調整 (${list(state.inspection?.requirements?.psgSongs).length})</button><button type="button" class="btn-sm" data-action="background-adjust"${!list(state.inspection?.requirements?.backgrounds).length ? ' disabled' : ''}>画像調整 (${list(state.inspection?.requirements?.backgrounds).length})</button><button type="button" class="btn-sm" data-action="sprite-adjust"${!list(state.inspection?.requirements?.sprites).length ? ' disabled' : ''}>立ち絵調整 (${list(state.inspection?.requirements?.sprites).length})</button><span>設定は正式export成功時だけsidecarへ保存</span></div>
        ${mappingsHtml()}${summaryHtml()}<div class="pce-gb-export-diagnostics">${diagnosticHtml()}</div><p class="form-hint ${esc(state.statusLevel)}">${esc(state.status)}${state.inspectionStale ? '（Preflight再実行が必要）' : ''}</p><div class="form-actions-inline modal-actions-end"><button type="button" class="btn-sm" data-action="cancel"${state.busy ? ' disabled' : ''}>キャンセル</button><button type="button" class="btn-sm" data-action="inspect"${state.busy ? ' disabled' : ''}>Preflight</button><button type="button" class="btn-primary" data-action="generate"${state.busy || state.inspectionStale || !state.inspection?.ok || !state.outputDir || (needsWarningConfirmation && !state.warningsAcknowledged) || (needsVisualConfirmation && !state.visualOmissionsConfirmed) ? ' disabled' : ''}>生成</button></div></div>`; };

      const bindMain = () => {
        const panel = modal.panel; panel.querySelectorAll('[data-action="cancel"]').forEach((button) => button.addEventListener('click', cancel));
        panel.querySelector('[data-action="pick-gb"]')?.addEventListener('click', async () => {
          const picked = await api.electronAPI.pickFile({ title: 'GB Studio 4.3.1/4.3.2実行ファイル', properties: ['openFile'], filters: [{ name: 'Executable', extensions: ['exe'] }] }); const selected = picked?.sourcePath || picked?.filePath || picked?.filePaths?.[0] || ''; if (!selected) return;
          try { await saveGbStudioExecutable(selected); state.gbStudioExecutable = selected; state.inspection = null; state.status = 'GB Studio実行ファイルを保存しました。'; state.statusLevel = 'info'; } catch (error) { state.status = `GB Studio設定保存失敗: ${error?.message || error}`; state.statusLevel = 'error'; } render();
        });
        panel.querySelector('[data-action="pick-output"]')?.addEventListener('click', async () => { const picked = await api.electronAPI.pickFile({ title: 'GB Studio出力folder', properties: ['openDirectory'] }); const selected = picked?.sourcePath || picked?.filePath || picked?.filePaths?.[0] || ''; if (selected) { state.outputDir = selected; render(); } });
        panel.querySelector('[data-action="pick-font"]')?.addEventListener('click', async () => { const picked = await api.electronAPI.pickFile({ title: 'BDF / TTF / OTF font', properties: ['openFile'], filters: [{ name: 'Font', extensions: ['bdf', 'ttf', 'otf', 'ttc'] }] }); const selected = picked?.sourcePath || picked?.filePath || picked?.filePaths?.[0] || ''; if (selected) { state.fontPath = selected; state.fontMode = 'custom'; state.inspectionStale = true; render(); } });
        panel.querySelector('[data-font-mode]')?.addEventListener('change', (event) => { state.fontMode = event.target.value; state.inspectionStale = true; state.visualOmissionsConfirmed = false; state.warningsAcknowledged = false; render(); }); panel.querySelector('[data-portrait-mode]')?.addEventListener('change', (event) => { state.portraitRenderMode = event.target.value === 'actor' ? 'actor' : 'baked'; state.portraitModeExplicit = true; state.inspectionStale = true; state.visualOmissionsConfirmed = false; state.warningsAcknowledged = false; state.spritePreview = null; render(); }); panel.querySelector('[data-mode]')?.addEventListener('change', (event) => { state.mode = event.target.value; }); panel.querySelector('[data-visual-confirm]')?.addEventListener('change', (event) => { state.visualOmissionsConfirmed = event.target.checked; render(); }); panel.querySelector('[data-warning-confirm]')?.addEventListener('change', (event) => { state.warningsAcknowledged = event.target.checked; render(); });
        panel.querySelectorAll('[data-cdda]').forEach((select) => select.addEventListener('change', () => { const id = select.dataset.cdda; state.cddaMappings[id] = select.value === '__external__' ? (state.cddaMappings[id]?.type === 'external-mod' ? state.cddaMappings[id] : { type: 'external-mod', source: '' }) : select.value; state.inspectionStale = true; render(); }));
        panel.querySelectorAll('[data-pick-mod]').forEach((button) => button.addEventListener('click', async () => { const picked = await api.electronAPI.pickFile({ title: 'GB Studio 4ch ProTracker MOD', properties: ['openFile'], filters: [{ name: 'ProTracker MOD', extensions: ['mod'] }] }); const selected = picked?.sourcePath || picked?.filePath || picked?.filePaths?.[0] || ''; if (selected) { state.cddaMappings[button.dataset.pickMod] = { type: 'external-mod', source: selected }; state.inspectionStale = true; render(); } }));
        panel.querySelectorAll('[data-substitution]').forEach((select) => select.addEventListener('change', () => { const id = select.dataset.substitution; const frequency = panel.querySelector(`[data-frequency="${id}"]`); state.audioSubstitutions[id] = { type: select.value, frequency: Number(frequency?.value) || 440, duration: 0.08 }; state.inspectionStale = true; }));
        panel.querySelectorAll('[data-frequency]').forEach((input) => input.addEventListener('change', () => { const id = input.dataset.frequency; state.audioSubstitutions[id] = { ...(state.audioSubstitutions[id] || { type: 'tone', duration: 0.08 }), frequency: Number(input.value) || 440 }; state.inspectionStale = true; }));
        panel.querySelector('[data-action="music-adjust"]')?.addEventListener('click', () => { state.view = 'music'; state.previewError = ''; render(); scheduleMusicPreview(); }); panel.querySelector('[data-action="background-adjust"]')?.addEventListener('click', () => { state.view = 'background'; state.previewError = ''; render(); scheduleBackgroundPreview(); }); panel.querySelector('[data-action="sprite-adjust"]')?.addEventListener('click', () => { state.view = 'sprite'; state.previewError = ''; render(); scheduleSpritePreview(); }); panel.querySelector('[data-action="inspect"]')?.addEventListener('click', () => void inspect()); panel.querySelector('[data-action="generate"]')?.addEventListener('click', () => void generate());
      };

      const bindMusic = () => {
        const panel = modal.panel; panel.querySelector('[data-action="back"]')?.addEventListener('click', () => { stopAudio(); state.view = 'main'; render(); }); panel.querySelector('[data-music-asset]')?.addEventListener('change', (event) => { stopAudio(); state.selectedMusic = event.target.value; state.musicPreview = null; render(); scheduleMusicPreview(); });
        const updateTempo = (value) => { ensureMusic(state.selectedMusic).tempoScale = Math.round(clamp(value, 50, 200, 100)); markAdjusted(); scheduleMusicPreview(); };
        panel.querySelector('[data-music-tempo]')?.addEventListener('input', (event) => { panel.querySelector('[data-music-tempo-number]').value = event.target.value; updateTempo(event.target.value); }); panel.querySelector('[data-music-tempo-number]')?.addEventListener('change', (event) => { updateTempo(event.target.value); render(); });
        panel.querySelectorAll('[data-music-channel]').forEach((input) => input.addEventListener('change', () => { const channel = Number(input.dataset.musicChannel); const field = input.dataset.field; const value = field === 'target' || (field === 'instrument' && input.value === 'auto') ? input.value : Number(input.value); ensureMusic(state.selectedMusic).channels[channel][field] = value; markAdjusted(); scheduleMusicPreview(); }));
        panel.querySelector('[data-action="reset-music"]')?.addEventListener('click', () => { state.music[state.selectedMusic] = defaultMusicSetting(); markAdjusted(); render(); scheduleMusicPreview(); }); panel.querySelector('[data-action="reset-all-music"]')?.addEventListener('click', () => { state.music = {}; list(state.inspection?.requirements?.psgSongs).forEach((item) => ensureMusic(item.id)); markAdjusted(); render(); scheduleMusicPreview(); });
        panel.querySelector('[data-play="source"]')?.addEventListener('click', () => void playPreview(state.musicPreview?.sourcePreview)); panel.querySelector('[data-play="gb"]')?.addEventListener('click', () => void playPreview(state.musicPreview?.gbPreview)); panel.querySelector('[data-action="stop-audio"]')?.addEventListener('click', stopAudio); panel.querySelector('[data-preview-loop]')?.addEventListener('change', (event) => { state.previewLoop = event.target.checked; });
      };

      const bindBackground = () => {
        const panel = modal.panel; panel.querySelector('[data-action="back"]')?.addEventListener('click', () => { state.view = 'main'; render(); });
        panel.querySelector('[data-background-asset]')?.addEventListener('change', (event) => { state.selectedBackground = event.target.value; const selected = list(state.inspection?.requirements?.backgrounds).find((item) => item.id === state.selectedBackground); state.selectedBackgroundFullScreen = Boolean(list(selected?.variants)[0]?.fullScreen); state.backgroundPreview = null; render(); scheduleBackgroundPreview(); }); panel.querySelector('[data-background-variant]')?.addEventListener('change', (event) => { state.selectedBackgroundFullScreen = event.target.value === '1'; state.backgroundPreview = null; render(); scheduleBackgroundPreview(); }); panel.querySelector('[data-background-mode]')?.addEventListener('change', (event) => { state.backgroundMode = event.target.value; render(); });
        const updateNumber = (field, value, min, max, fallback) => { ensureBackground(state.selectedBackground)[field] = clamp(value, min, max, fallback); markAdjusted(); scheduleBackgroundPreview(); };
        panel.querySelectorAll('[data-background-field]').forEach((input) => input.addEventListener('input', () => { const field = input.dataset.backgroundField; const limits = field === 'brightness' ? [-100, 100, 0] : [0, 200, 100]; panel.querySelector(`[data-background-number="${field}"]`).value = input.value; updateNumber(field, input.value, ...limits); }));
        panel.querySelectorAll('[data-background-number]').forEach((input) => input.addEventListener('change', () => { const field = input.dataset.backgroundNumber; const limits = field === 'brightness' ? [-100, 100, 0] : [0, 200, 100]; updateNumber(field, input.value, ...limits); render(); })); panel.querySelectorAll('[data-background-dither]').forEach((input) => input.addEventListener('change', () => { ensureBackground(state.selectedBackground)[input.dataset.backgroundDither] = input.checked; markAdjusted(); scheduleBackgroundPreview(); }));
        panel.querySelector('[data-action="reset-background"]')?.addEventListener('click', () => { state.backgrounds[state.selectedBackground] = defaultBackgroundSetting(); markAdjusted(); render(); scheduleBackgroundPreview(); }); panel.querySelector('[data-action="reset-all-backgrounds"]')?.addEventListener('click', () => { state.backgrounds = {}; list(state.inspection?.requirements?.backgrounds).forEach((item) => ensureBackground(item.id)); markAdjusted(); render(); scheduleBackgroundPreview(); });
      };
      const bindSprite = () => {
        const panel = modal.panel; panel.querySelector('[data-action="back"]')?.addEventListener('click', () => { stopSpriteAnimation(); state.view = 'main'; render(); });
        panel.querySelector('[data-sprite-asset]')?.addEventListener('change', (event) => { stopSpriteAnimation(); state.selectedSprite = event.target.value; const selected = list(state.inspection?.requirements?.sprites).find((item) => item.id === state.selectedSprite); state.selectedSpriteScene = list(selected?.usageSceneIds)[0] || ''; state.selectedSpriteAnimation = list(selected?.animations)[0]?.id || ''; state.spritePreview = null; state.spriteFrame = 0; render(); scheduleSpritePreview(); }); panel.querySelector('[data-sprite-scene]')?.addEventListener('change', (event) => { state.selectedSpriteScene = event.target.value; state.spritePreview = null; render(); scheduleSpritePreview(); }); panel.querySelector('[data-sprite-animation]')?.addEventListener('change', (event) => { stopSpriteAnimation(); state.selectedSpriteAnimation = event.target.value; state.spritePreview = null; state.spriteFrame = 0; render(); scheduleSpritePreview(); }); panel.querySelector('[data-sprite-mode]')?.addEventListener('change', (event) => { stopSpriteAnimation(); state.spriteMode = event.target.value === 'dmg' ? 'dmg' : 'gbc'; state.spritePreview = null; state.spriteFrame = 0; render(); scheduleSpritePreview(); });
        const limits = { scale: [25, 200, 100], offsetX: [-320, 320, 0], offsetY: [-224, 224, 0], brightness: [-100, 100, 0], saturation: [0, 200, 100] }; const updateNumber = (field, value) => { const [min, max, fallback] = limits[field]; ensureSprite(state.selectedSprite)[field] = clamp(value, min, max, fallback); markAdjusted(); scheduleSpritePreview(); };
        panel.querySelectorAll('[data-sprite-field]').forEach((input) => input.addEventListener('input', () => { const field = input.dataset.spriteField; const peer = panel.querySelector(`[data-sprite-number="${field}"]`); if (peer) peer.value = input.value; updateNumber(field, input.value); })); panel.querySelectorAll('[data-sprite-number]').forEach((input) => input.addEventListener('change', () => { updateNumber(input.dataset.spriteNumber, input.value); render(); }));
        panel.querySelectorAll('[data-sprite-crop]').forEach((input) => input.addEventListener('change', () => { const setting = ensureSprite(state.selectedSprite); const base = setting.crop || state.spritePreview?.crop || { x: 0, y: 0, width: 1, height: 1 }; const field = input.dataset.spriteCrop; const minimum = field === 'width' || field === 'height' ? 1 : 0; setting.crop = { ...base, [field]: Math.round(clamp(input.value, minimum, 4096, minimum || 1)) }; markAdjusted(); render(); scheduleSpritePreview(); })); panel.querySelectorAll('[data-sprite-dither]').forEach((input) => input.addEventListener('change', () => { ensureSprite(state.selectedSprite)[input.dataset.spriteDither] = input.checked; markAdjusted(); scheduleSpritePreview(); }));
        panel.querySelector('[data-action="copy-sprite"]')?.addEventListener('click', () => { const { sourceHash: _sourceHash, ...portable } = ensureSprite(state.selectedSprite); state.spriteClipboard = copy(portable); state.status = `立ち絵設定をcopyしました: ${state.selectedSprite}`; state.statusLevel = 'info'; render(); }); panel.querySelector('[data-action="paste-sprite"]')?.addEventListener('click', () => { if (!state.spriteClipboard) return; const sourceHash = ensureSprite(state.selectedSprite).sourceHash || ''; state.sprites[state.selectedSprite] = { ...defaultSpriteSetting(), ...copy(state.spriteClipboard), sourceHash }; markAdjusted(); render(); scheduleSpritePreview(); }); panel.querySelector('[data-action="reset-sprite"]')?.addEventListener('click', () => { state.sprites[state.selectedSprite] = defaultSpriteSetting(); markAdjusted(); render(); scheduleSpritePreview(); }); panel.querySelector('[data-action="reset-all-sprites"]')?.addEventListener('click', () => { state.sprites = {}; list(state.inspection?.requirements?.sprites).forEach((item) => ensureSprite(item.id)); markAdjusted(); render(); scheduleSpritePreview(); });
        panel.querySelector('[data-action="play-sprite"]')?.addEventListener('click', () => { state.spritePlaying = true; state.spriteFrame = 0; render(); scheduleSpritePlayback(); }); panel.querySelector('[data-action="stop-sprite"]')?.addEventListener('click', () => { stopSpriteAnimation(); render(); }); panel.querySelector('[data-sprite-loop]')?.addEventListener('change', (event) => { state.spriteLoop = event.target.checked; });
      };
      const render = () => { modal.panel.innerHTML = state.view === 'music' ? musicHtml() : state.view === 'background' ? backgroundHtml() : state.view === 'sprite' ? spriteHtml() : mainHtml(); if (state.view === 'music') bindMusic(); else if (state.view === 'background') bindBackground(); else if (state.view === 'sprite') bindSprite(); else bindMain(); };

      const inspect = async () => {
        if (!state.gbStudioExecutable) { state.status = 'GB Studio 4.3.1または4.3.2を選択してください。'; state.statusLevel = 'error'; render(); return; }
        if (state.fontMode === 'custom' && !state.fontPath) { state.status = 'font fileを選択してください。'; state.statusLevel = 'error'; render(); return; }
        state.busy = true; state.status = 'BG量子化・font page・BGMをpreflight中…'; state.statusLevel = ''; render();
        try {
          const inspection = await invoke('inspectVnGbStudioExport', payload()); state.inspection = inspection;
          if (!state.settingsLoaded) { state.music = copy(inspection.settings?.music); state.backgrounds = copy(inspection.settings?.backgrounds); state.sprites = copy(inspection.settings?.sprites); state.portraitRenderMode = inspection.settings?.portraitRenderMode === 'actor' ? 'actor' : 'baked'; state.portraitModeExplicit = false; state.settingsLoaded = true; }
          list(inspection.requirements?.cdda).forEach((requirement) => { if (!state.cddaMappings[requirement.id] && requirement.mapping) state.cddaMappings[requirement.id] = requirement.mapping; });
          list(inspection.requirements?.audioSubstitutions).forEach((requirement) => { if (!state.audioSubstitutions[requirement.id]) state.audioSubstitutions[requirement.id] = requirement.mapping && typeof requirement.mapping === 'object' ? requirement.mapping : { type: 'tone', frequency: 440, duration: 0.08 }; });
          const songs = list(inspection.requirements?.psgSongs); const backgrounds = list(inspection.requirements?.backgrounds); const sprites = list(inspection.requirements?.sprites); if (!state.selectedMusic && songs.length) state.selectedMusic = songs[0].id; if (!state.selectedBackground && backgrounds.length) { state.selectedBackground = backgrounds[0].id; state.selectedBackgroundFullScreen = Boolean(list(backgrounds[0].variants)[0]?.fullScreen); } if (!state.selectedSprite && sprites.length) { state.selectedSprite = sprites[0].id; state.selectedSpriteScene = list(sprites[0].usageSceneIds)[0] || ''; state.selectedSpriteAnimation = list(sprites[0].animations)[0]?.id || ''; }
          state.inspectionStale = false; state.status = inspection.ok ? `Preflight完了: warning ${inspection.warnings.length}件 / visual省略 ${list(inspection.audits?.visual?.omissions).length}件` : `Preflight停止: error ${inspection.errors.length}件`; state.statusLevel = inspection.ok ? 'info' : 'error';
        } catch (error) { state.status = `Preflight失敗: ${error.message || error}`; state.statusLevel = 'error'; } finally { state.busy = false; render(); }
      };
      const generate = async () => {
        if (!state.outputDir) { state.status = '出力folderを選択してください。'; state.statusLevel = 'error'; render(); return; }
        state.busy = true; state.status = '最新設定で再preflight中…'; state.statusLevel = ''; render();
        try {
          const latest = await invoke('inspectVnGbStudioExport', payload()); state.inspection = latest; state.inspectionStale = false; if (!latest.ok) throw new Error(`preflight error ${latest.errors.length}件`);
          state.status = 'GB Studio projectを生成中…'; render(); const result = await invoke('exportVnGbStudioProject', { ...payload(), outputDir: state.outputDir, mode: state.mode }); if (typeof saveSnapshot === 'function') await saveSnapshot(doc); logger?.info?.(`GB Studio projectを出力しました: ${result.outputDir}`); finish({ ok: true, message: `GB Studio projectを出力しました: ${result.outputDir}`, result });
        } catch (error) { state.status = `生成失敗: ${error.message || error}`; state.statusLevel = 'error'; logger?.error?.(state.status); state.busy = false; render(); }
      };

      window.addEventListener('keydown', onKeyDown); render(); modal.open(); if (state.gbStudioExecutable) void inspect();
    });
  };

  const run = async (editor = {}) => { if (typeof editor.getSnapshot !== 'function') throw new Error('Novel editor action APIが不足しています'); const doc = await editor.getSnapshot(); const assets = typeof editor.getAssets === 'function' ? await editor.getAssets() : []; return openExporter({ doc, assets, saveSnapshot: editor.saveSnapshot }); };
  registerCapability('vn-gb-studio-exporter', { pluginId: plugin.id, label: 'GB Studio出力', openExporter });
  registerCapability('novel-toolbar-action', { id: 'gb-studio-export', pluginId: plugin.id, label: 'GB Studio出力', title: 'GB/GBC両対応のGB Studio 4.3.1/4.3.2 projectへ変換', priority: 100, order: 30, placement: 'after-preview', run });
}
